### ISSUE TITLE
Drug program, Protocol, Product field inconsistency

### ISSUE THREAD

**Issue by andmiel81** [DBMS-Consulting/CQT2#100]
![image](https://cloud.githubusercontent.com/assets/22034392/23584289/d14e1596-0154-11e7-96d9-92976aeb5c81.png)

See the notes in the screenshot.

This issue is also visible in "details", and "confirm" tabs.

**Comment by zmeenakshi** [comment]
The system should save codelist_interval_values, but on search and other places (details, confirm) it should  display codelist_values and also records will be searched based on codelist_values. Moreover I still can't don't see the Pfizer data. 

![image](https://cloud.githubusercontent.com/assets/25993316/23584871/540d01e2-0194-11e7-8420-fa4bfa9eaf12.png)

**Comment by zmeenakshi** [comment]
Typo: It is internal NOT interval.

![image](https://cloud.githubusercontent.com/assets/25993316/23584907/266c6f06-0195-11e7-9fa4-c2b6288df5a1.png)
