### ISSUE TITLE
Dicionary Version and Name the two fields at the bottom swapped on different form. 

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#102]
Modules: All
Forms: Search, Details, Informative Notes and Confirm

The display order should be same on all form:
Dictionary Name:                             Version:

![image](https://cloud.githubusercontent.com/assets/25993316/23586001/770201d4-01b2-11e7-87aa-d4d7a24b0c82.png)

INCORRECTLY mapped in the DETAILS form: Name field is displaying Version and version field is displaying Name.

![image](https://cloud.githubusercontent.com/assets/25993316/23586008/972daf12-01b2-11e7-8cd6-beaf85794982.png)

**Comment by andmiel81** [comment]
This is already fix by @lsalim 's commit b2634c9
