### ISSUE TITLE
[Update/Copy] Not displaying Details of selected list, previously working.

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#104]
Module: Update/Copy
Page: Search/Details

When selecting a result, the Details in some fields do not display correctly.

This was working before, please fix **AND** find out how it was broken and in what commit, and let me know.

![image](https://cloud.githubusercontent.com/assets/12534580/23590235/39ca477a-01aa-11e7-8788-f61e800ae8cd.png)
![image](https://cloud.githubusercontent.com/assets/12534580/23590243/52195942-01aa-11e7-97ca-32df8e2022be.png)

**Comment by andmiel81** [comment]
Checked this.
This is not a bug.
It seems that this record has been created some time ago, when the "Drug program", "protocol", "product" are saved as text value not config list internal code.
