### ISSUE TITLE
[UPDATE] Bug, Relations delete button deleted ALL relations, not just one row.

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#110]
Module: Update
Page; Relations

Clicking the Delete button on the row of a relation just correctly deleted that one row in UI, Save button was click, but when searching again for that list and viewing relations, ALL relations had actually been deleted.

**Comment by zmeenakshi** [comment]
Viresh has reversed code update done for Delete Selected. The issue with row level deleted has been fix. Viresh is going to code Delete Selected tomorrow.
