### ISSUE TITLE
[HIERARCHY SEARCH] Hierarchy Search pop-up window goes off-screen on smaller resolutions

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#111]
Module: Create/Update/Copy
Page: Relations/Hierarchy Search
Priority: High (to be done immediately)

The laptops the customers use have smaller screens, it turns out that the Hierarchy Search popup default size is too large for their windows. Needs to be standardized for all resolutions.

Also, need to add something to stop any of the borders of the popup from EVER moving outside the borders of the browser/screen.

**Comment by zmeenakshi** [comment]
Hierarchy search pop up window is locked to title bar and unmoveable.

![image](https://cloud.githubusercontent.com/assets/25993316/23696210/c1760b2c-0408-11e7-9aa8-a38eb3757c5e.png)

**Comment by andmiel81** [comment]
I can' t reproduce the same bug even in a small resolution.
Please try again after cleaning your browser cache.

**Comment by andmiel81** [comment]
confirm please

**Comment by zmeenakshi** [comment]
Fixed.

**Comment by zmeenakshi** [comment]
Hierarchy search pop up window is locked to title bar and unmoveable.
Once user expands a list the window length expands, instead window should have a scroll-bar to scroll-down or up to view the terms.

![image](https://cloud.githubusercontent.com/assets/25993316/24596497/56483df2-185d-11e7-963f-3867c69dc8e6.png)

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24643416/74a037b8-192b-11e7-9d00-6a040fc8c361.png)
