### ISSUE TITLE
The State drop-down on Search page should show what is the active ('Y') in Workflow state codelist. This should  work same as the Product, Extension, Protocol and Program drop-downs.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#113]
Module: Browse & Search/Update/Copy
Form: Search
Priority : High (To be completed on 7-March-2017)

Expected: 
![image](https://cloud.githubusercontent.com/assets/25993316/23644185/09415fa2-032c-11e7-865f-b7b6b7e0f693.png)

Currently showing hard-coded values:
![image](https://cloud.githubusercontent.com/assets/25993316/23644201/236e775c-032c-11e7-8529-2cc1bb864b0e.png)

**Comment by lsalim** [comment]
Fixed! Commit done.
