### ISSUE TITLE
All Modules: Navigating from one to another by clicking on the tab is not working correctly.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#115]
The tab selected in **Confirm** whereas form opened in **Relations**.
Priority: High (to be completed on 7th March)

![image](https://cloud.githubusercontent.com/assets/25993316/23657304/6a6e52f8-0363-11e7-9327-bf40e6a37a53.png)

**Comment by lsalim** [comment]
Must be an error in Relations tab. Looking into it

**Comment by zmeenakshi** [comment]
In addition:
When user move directly from Search to Confirm, they are not able to move state to next workflow. This causes the hanging state.

**Comment by zmeenakshi** [comment]
Update module -> When user moves directly Confirm tab to Search tab, search page is not refreshed per the new filter criteria. It continues to display old search results.

**Comment by zmeenakshi** [comment]
Update module -> When user moves directly Confirm tab to Search tab, search page is not refreshed per the new filter criteria. It continues to display old search results.

![image](https://cloud.githubusercontent.com/assets/25993316/23900268/80378002-08de-11e7-88a9-5ae6582079ce.png)

**Comment by zmeenakshi** [comment]
Update module -> 
=> When user moves directly Confirm tab to Search tab, search page is not refreshed per the new filter criteria. It continues to display old search results. (NOT RESOLVED)

=> When user moves directly Relations tab to Search tab, search page is not refreshed per the new filter criteria. It continues to display old search results.
