### ISSUE TITLE
Replace Term with List on the Search form.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#117]
Modules: Update/Copy/Browse & Search
Form: Search
Priority : HIGH (Complete on 7th March 2017)

Replace Term with **List Name**
![image](https://cloud.githubusercontent.com/assets/25993316/23666680/b9e30a22-0381-11e7-8601-4c0ebc7c1380.png)

**Comment by lsalim** [comment]
Fixed and committed
