### ISSUE TITLE
Due Date and Reason for approval are not cleared when Confirm it refreshed.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#119]
Completion Date: 13-March-2017
Module: Create/Update/Copy
Form: Confirm.

Due date will change for every workflow state, so it should not show the previously entered date in the Due date field, and the same is applicable for Request for Reason (CMQ_WF_DESC) and Reason for  approval: CMQ_APPROVE_REASON. .

Note: Added column for Reason for  Approval: CMQ_APPROVE_REASON in the DB today. 

![image](https://cloud.githubusercontent.com/assets/25993316/23699189/3fd24c14-0414-11e7-9b30-9a3837ac7161.png)

**Comment by lsalim** [comment]
Due date is cleared after confirm.

**Comment by lsalim** [comment]
'CMQ_APPROVE_REASON' is not present is DB

**Comment by zmeenakshi** [comment]
CMQ_APPROVE_REASON has been added in the database.

Also, data is NOT saved form CMQ_WF_DESC.
