### ISSUE TITLE
Some default Description is stored in the DB, when Details are saved.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#121]
Completion Date: 8-March-2017
Module: Create
Form: Details

Querying CMQ_BASE_CURRENT in showing *** Description*** in the DB when Details are saved. 
Note: This is before adding and saving Add Informative Notes.

![image](https://cloud.githubusercontent.com/assets/25993316/23699369/ea876d42-0414-11e7-9287-f011d76cb2fa.png)

**Comment by lsalim** [comment]
Description has property not null. We needed a default value to save the details before saving the real description typed by the user.

**Comment by zmeenakshi** [comment]
Can we save "Please enter the description" as default instead of ***Description***
