### ISSUE TITLE
Create -> Details: The Protocol field is empty when navigating to Add Details form and the default extension is TME.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#122]
Module: Create
Form: Details

![image](https://cloud.githubusercontent.com/assets/25993316/23700490/efce8516-0418-11e7-8ad4-4def0bfd7ef0.png)

**Comment by lsalim** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/5912923/23718847/fc1b8752-0430-11e7-8376-a78c838dece3.png)
