### ISSUE TITLE
Publish -> Publish Current Version. Modify the code to update CMQ_STATUS and add rule 3.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#126]
To complete on 10th March 2017.
Module->Publish -> Publish Current Version
Promote to Publish: Publishing a list will change CMQ_STATE from Approved to Published and CMQ_STATUS P to A. (Add 
Rule 1: If level 1 list does not have any associated child, Publish the list. Displays a message, "The List is Published and Activated successfully." : Add STATUS change
Rule 2: Associated lists (parent and child) are published together. Displays a message "The List(s)s are Published and Activated successfully" - Add STATUS change. If both lists lists are selected then display a warning message, "The List being promoted has an associated list that must be promoted." and do *NOT* publish the list.
New Rule: For level 2 list if the columns CMQ_PARENT_CODE and CMQ_PARENT_NAME are blank then display an error "The List does not have an associated parent list, hence cannot be Published and Activated"

**Comment by lsalim** [comment]
Commit done. Please test to confirm if fixed.

**Comment by zmeenakshi** [comment]
Not working as explained above. Please fix it.
