### ISSUE TITLE
On saving Relations, the save confirmation message is no longer appearing.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#128]
Completion: 10th March 2017
Module : Copy/Update/Create
Form: Relations

On saving Relations, the save confirmation message is no longer appearing.

**Comment by lsalim** [comment]
Cannot test it. Relations has an issue.

**Comment by lsalim** [comment]
It is working now

**Comment by zmeenakshi** [comment]
NO save message is displayed.

**Comment by andmiel81** [comment]
fixed by 4e2893c
