### ISSUE TITLE
Search page is not displaying correct State once workflow state is updated and users searches the list without exiting the Update module.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#130]
Module- Update
Form: Search
Completed by: 13th March 2017

Search page is not displayed correct State when workflow state is move from one WF state to another and users searches the list without exiting the Update module.

![image](https://cloud.githubusercontent.com/assets/25993316/23783589/a5eba1ac-0582-11e7-9ae6-29daf689cb90.png)

![image](https://cloud.githubusercontent.com/assets/25993316/23783653/2579ec4e-0583-11e7-9dd8-32deca7fc1a5.png)

**Comment by andmiel81** [comment]
done by f657d41b23b651061d072fddf208cf879343ec18
