### ISSUE TITLE
Module Reports -> Reports -> List Details

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#132]
Completion Date: 14th March 2017

The Report drop-down should show -> Generate List Details
If start date and end date are entered then the reports should show the Lists activated between start and end date. and the Status is Active and State is Published.
If no start date and end date are provided then the reports should display all lists which are Active and Published.
If only Start date is provided, then all lists which are Active and Published between start date and list generation date.
Posted report format (excel) on skype "CQT-Reports-Generate List Details - List Details"
Same is required in PDF also.

*Please ask Alexander to provide you the new logo.

**Comment by zmeenakshi** [comment]
Report generating in Excel and PDF is not working.

**Comment by zmeenakshi** [comment]
There is any issue with report generation when specifying date. The system show a message that "No record matching record found" if no list with matching activation date are found in DB. Not some wrong (random) message.

![image](https://cloud.githubusercontent.com/assets/25993316/23987917/f306486a-0a51-11e7-83db-e7b5e16e2de0.png)

**Comment by andmiel81** [comment]
PDF report added in commit 94652e56c231cd574ee193d3fd21c87409b5796c

**Comment by andmiel81** [comment]
confirm please

**Comment by zmeenakshi** [comment]
Still getting issue mentioned above: "There is an issue with report generation when specifying date. The system should show a message that "No matching record found" if no list with matching activation date are found in the DB, NOT some wrong (random) message."

![image](https://cloud.githubusercontent.com/assets/25993316/24183684/e05f92d2-0eef-11e7-89d4-cc0228053399.png)

**Comment by andmiel81** [comment]
fixed by f3c41fd5c014f37a2ef554fd8280af772ef784f1
