### ISSUE TITLE
Change tab title under Reports module

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#133]
Complete by: 14th March 2017

Replace tab name Lists with Administration Report

![image](https://cloud.githubusercontent.com/assets/25993316/23829759/3613f434-0720-11e7-9ac8-ee53f3538166.png)

Replace tab name Reports with Lists
![image](https://cloud.githubusercontent.com/assets/25993316/23829773/845f8810-0720-11e7-9c3f-eae2109ade46.png)

**Comment by andmiel81** [comment]
done by commit c7982a3
