### ISSUE TITLE
Miscellaneous minor issues.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#135]
=> Add Details: The initial default value for list type TME is not correct. Drug Program and Protocol should be blank.

![image](https://cloud.githubusercontent.com/assets/25993316/23842963/6d149cb8-07de-11e7-89c0-ed56aa300ee0.png)

=> The default value for lists other than TME, PRO, DME, TR1, CPT should be as following:
Drug Program : No Program
Protocol: No Protocol
Product: No Product
Level: 1
Algorithm, Status, State and Group as a other lists.

=> The Status and State should be upper on all form:

![image](https://cloud.githubusercontent.com/assets/25993316/23843026/f37750a2-07de-11e7-9244-1d0fa7e4e4b1.png)

![image](https://cloud.githubusercontent.com/assets/25993316/23843045/1573366c-07df-11e7-9bda-7125b1063f64.png)

=> Page title bar with home icon is missing:

![image](https://cloud.githubusercontent.com/assets/25993316/23843156/d5b18140-07df-11e7-8371-6737c7f39fe0.png)

=> Save button is active for list where State is Approved.
![image](https://cloud.githubusercontent.com/assets/25993316/23843594/09480bfc-07e3-11e7-949e-2ffa754c1fc3.png)

=> The PRO is appearing in Level drop-down in Hierarchy Search for CPT and DME lists.
![image](https://cloud.githubusercontent.com/assets/25993316/23844030/a7fe2e6e-07e5-11e7-91bf-2ddd2c67775b.png)

**Comment by lsalim** [comment]
For the last issue, it was : WHEN EXTENSION equals PRO, do not show it in the Hierarchy Dropdown. Or Am I mistaken?

**Comment by zmeenakshi** [comment]
=> When I open the Add Details, the initial values are what is shown in the screenshot. After that it changes per extension selection.

=> Hierarchy Search: if current list is PRO, CPT or DME then PRO should not be displayed in the level drop-down.

**Comment by zmeenakshi** [comment]
=> Why is Protocol blank for TME and Product "No Product"

![image](https://cloud.githubusercontent.com/assets/25993316/24030589/af2a3a72-0b03-11e7-8649-be75313cb427.png)

=> Don't think you fixed following:
=> The default value for lists other than TME, PRO, DME, TR1, CPT should be as following:
Drug Program : No Program
Protocol: No Protocol
Product: No Product

![image](https://cloud.githubusercontent.com/assets/25993316/24030640/fb91a44a-0b03-11e7-81b6-4e1ad05d64c5.png)

**Comment by zmeenakshi** [comment]
The default value for lists other than TME, PRO, DME, TR1, CPT should be basically the codelist items marked as Active and Default in the respective codelist.
Presently, the default flag in 'Y' for No Product in Product code, No Protocol in Protocol codelist and No Program in Program codelist. But in future if Administrator changes the default value to a different codelist value "example; Default flag is set to 'Y' for  All Product ", in that case the new default value which is 'All Product' should be displayed as default for the Product in the Add Details form.

**Comment by zmeenakshi** [comment]
Opened new ticket for the last update on the ticket.
