### ISSUE TITLE
Search Level ALL and and Reset button in Browse & Search / Update -> Search.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#140]
*ASAP*

Level ALL search and Reset button is not working consistently in 8080.
It seems Reset becomes unresponsive when moving from Confirm to Search or Relations to Search.

**Comment by acoughlin** [comment]
- Group should always reset No Group, sometimes resets to ALL
- Search result table does not update after selecting a result, then going back and reseting and trying a new search... so it is impossible to test the searching functionality until this is fixed
- After selecting a result and going back to search, every field does not reset but stays the same as previously selected list values
- Level is resetting to ALL, should reset to 1
- Drug Program/Protocol/Product need to reset to *blank*
- Extension needs to reset to All
