### ISSUE TITLE
Fix form resolution and layout.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#142]
All Modules
Form: Confirm:
![image](https://cloud.githubusercontent.com/assets/25993316/24031850/d71f3e4a-0b0a-11e7-879e-cd8d7e289258.png)

and same for Details also.

**Comment by zmeenakshi** [comment]
The sections still don't apear aligned. **Reduce** the space between column.

**Comment by andmiel81** [comment]
confirm please
