### ISSUE TITLE
Details: Disable Algorithm field.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#150]
All Modules
Form: Details

Disable algorithm field.

![image](https://cloud.githubusercontent.com/assets/25993316/24037254/2c7207c0-0b23-11e7-8de9-e13a7e755a38.png)

**Comment by zmeenakshi** [comment]
Fixed Details: Disable Algorithm field. #150

**Comment by singhsg** [comment]
We need some kind of codelist to determine whether or not the algorithm is enabled/disabled.
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by zmeenakshi** [comment]
I think we need configuration for all fields, which can be added in the next release?

RS: UR-3.1.9-560: The solution shall provide the ability to configure  list types for designating fields that are displayed or hidden
a.	Hiding and displaying fields
