### ISSUE TITLE
Hierarchy Search: the term field is pre-filled with previous search string.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#154]
All Modules
Form: Hierarchy Search

The terms field is displayed search text entered previously.
=>Searched for PRO in Hierarchy Search.
=> After adding and saving term.
=> Search another list in Update->Search
=> Select list and moved to Relations form
=> Opened Hierarchy Search, the term search previously is displayed.

![image](https://cloud.githubusercontent.com/assets/25993316/24095358/caed318e-0d82-11e7-8851-67f7a1e33727.png)

**Comment by andmiel81** [comment]
confirm please
