### ISSUE TITLE
All dates (CREATION_DATE, LAST_ACTIVATION_DATE and LAST_MODIFICATION_DATE) should be saved in eastern time zone.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#156]
All dates (CREATION_DATE, LAST_ACTIVATION_DATE and LAST_MODIFICATION_DATE) should be saved in eastern time zone.

**Comment by andmiel81** [comment]
When we use the java.util.Date to serialize Date/time, the timezone is implicitely UTC.
So I am thinking the possible solution would be saving in UTC into DB, and convert it to local time(EST) when shown on UI. (this has already been performed with commit d829f3370fd5296ed04ee1875a7a50734eba69d3)

**Comment by zmeenakshi** [comment]
This is not just a display issue. All dates (CREATION_DATE, LAST_ACTIVATION_DATE and LAST_MODIFICATION_DATE) should be saved in eastern time zone.

**Comment by zmeenakshi** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/25993316/24597665/b9609676-1864-11e7-9c70-a73ffd28e379.png)


![image](https://cloud.githubusercontent.com/assets/25993316/24597673/c9ee8a0c-1864-11e7-86ec-0b0b1b58224a.png)
