### ISSUE TITLE
Update Impact Assessment (remove Search fields)

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#157]
Module: Impact Assessment
Page: Impact Assessment

Remove Term and Search and Level fields

See the older ADF version vs. the current version. Just remove those fields so it is the same.
![image](https://cloud.githubusercontent.com/assets/12534580/24114919/2445b0a4-0d78-11e7-953d-f2c9ca633b82.png)
![image](https://cloud.githubusercontent.com/assets/12534580/24114923/27ed4f46-0d78-11e7-9797-6887b789d597.png)

**Comment by andmiel81** [comment]
fixed on commit e94c7873bc73b182d3525c3be88f46c7fa295ec6
