### ISSUE TITLE
Impact Search window - Fix cancel button, inner frame border, column should be resizeable.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#161]
**High Priority**
22-March-2017
Module: Impact Assessment
Form: Impact Search

![image](https://cloud.githubusercontent.com/assets/25993316/24184194/c02bcb40-0ef2-11e7-928a-5a072996e15f.png)

**Comment by andmiel81** [comment]
the dialog made to be full-width intentionally for @vireshwali 's issue:
  Since no drag-n-drop has been implemented for this and only the "add selected" button is available, it is unnecessary to show both dialog and background tables.
