### ISSUE TITLE
Impact Assessment - Hierarchy Search

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#162]
**High Priority - 2**
Module: Impact Assessment
Form: Hierarchy Search

Fix:
1) Cancel button.
2) Inner frame border
3) Remove Filter and Sort button
4) The columns within the hierarchy search should be resizeable horizontally.

![image](https://cloud.githubusercontent.com/assets/25993316/24184334/7439227c-0ef3-11e7-9bef-dd7d87ff9663.png)

**Comment by andmiel81** [comment]
please confirm

**Comment by zmeenakshi** [comment]
1) We can increase the length of inner frame  as there is a lot of extra space.
2) Add "Add Selected" button to add term to the right section (Please not user should be able terms in left section)
3) I still see filter and sort button.

![image](https://cloud.githubusercontent.com/assets/25993316/24285481/3ef3c280-1096-11e7-945b-dc2a8aeee44d.png)

**Comment by andmiel81** [comment]
please check if this is still an issue.

**Comment by zmeenakshi** [comment]
Fixed.
