### ISSUE TITLE
Hierarchy Search: Add the condition to not show retired (cmq_status = 'I') level 2 lists in the hierarchy search.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#163]
Modules: Create, Update, Copy and Impact Assessment
Form Hierarchy Search

Hierarchy Search: Add the condition to not show retired (cmq_status = 'I') level 2 lists in the hierarchy search.

**Comment by vireshwali** [comment]
done.

**Comment by zmeenakshi** [comment]
Fixed.
