### ISSUE TITLE
Browse & Search -> Parent List - Associated Parent list is not displayed.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#165]
Module: Browse & Search
Form: Parent List

Associated Parent list is not displayed in the Parent List pop-up.

**Comment by vireshwali** [comment]
fixed. Please test

**Comment by zmeenakshi** [comment]
fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24596602/e7b04f78-185d-11e7-9e17-db61b02d5c54.png)
