### ISSUE TITLE
Impact Assessment, Next Button

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#168]
*Priority High - 1 *

Module: Impact Assessment
Page: Impact Assessment

Add Next button functionality

**Comment by zmeenakshi** [comment]
Next button functionality is not that straight forward here.
1) If user will select the list in the right  box and click Next, then it should show informative notes and details from target tables and should be read-only.
2) Whereas, if user will select the list in the left box and click Next, then it should show informative notes (all tabs) and details (only designee) from current table and should be editable.

**Comment by zmeenakshi** [comment]
IA details forms has not been as per skype chat:
![image](https://cloud.githubusercontent.com/assets/25993316/24438773/644eedd2-1467-11e7-818e-6bc2078e434c.png)

**Comment by zmeenakshi** [comment]
Two save button on Details forms.

![image](https://cloud.githubusercontent.com/assets/25993316/24490563/aa774276-1540-11e7-8ced-0c79c15f4457.png)

**Comment by zmeenakshi** [comment]
Add **Save** functionality code for Informative Notes and Details forms in IA forms (rules are same, the data will be updated only for CMQs and when right panel CMQ is selected).

**Comment by zmeenakshi** [comment]
=> I'm getting auto-save prompt on click Next button even after Saving informative note updates. I think Save button is **NOT** working correctly. It is **NOT** saving changes.

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/24642567/c8b81eac-1925-11e7-812b-077b08fd35f3.png)

Here is another issue related to Next in IA module and some missing data in details:
![image](https://cloud.githubusercontent.com/assets/25993316/24642596/fcae6950-1925-11e7-832c-97991bb67d0c.png)

![image](https://cloud.githubusercontent.com/assets/25993316/24642606/10bc51d2-1926-11e7-87c0-6cc211970e36.png)

**Comment by zmeenakshi** [comment]
Open a new ticket.
