### ISSUE TITLE
Reports -> Lists; Error message is not cleared.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#170]
Error message should clear after 3 seconds.

![image](https://cloud.githubusercontent.com/assets/25993316/24330383/5829402c-123a-11e7-944e-06a163d50684.png)

**Comment by andmiel81** [comment]
changed the messaging style, to be consistent with other modules.
Now message shows up on the top-right corner of the screen and automatically disappears after a few seconds.
