### ISSUE TITLE
Copy -> Details : Error message is displayed even though list attributes (CMQ_NAME and CMQ_EXTENSION) combination is not duplicate.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#173]
Module: Copy
Form: Details 

Issue: Error message is displayed even through list attributes (CMQ_NAME and CMQ_EXTENSION) combination is not duplicate. This is an intermittent issue, but happens consistently with some lists. One of these list/CMQ is TME_TEST2

![image](https://cloud.githubusercontent.com/assets/25993316/24330558/31348b1c-123e-11e7-898b-013a8a1a5b2e.png)

**Comment by vireshwali** [comment]
issue caused by child being copied in main list. Removed child copy from logic now as per meenakshi's advise.
