### ISSUE TITLE
Impact Assessment : Add filter for Term column in Impact Search form.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#176]
Module: Impact Assessment
Form: Impact Search

Add filter for Term column in Impacted Search form.

![image](https://cloud.githubusercontent.com/assets/25993316/24490700/6a001532-1541-11e7-8201-a1902aa682c4.png)

**Comment by zmeenakshi** [comment]
Add Extension/Level column in the Impact Search form and also add filter for Extension/Level column after Term column.

**Comment by andmiel81** [comment]
still needs work for extension and level search.
I am thinking of select box filtering. if that's wrong, plz let me know

**Comment by zmeenakshi** [comment]
=> Extension will be used for CMQs and Level for SMQs.
=> **I'm not clear what do you mean by select box filtering.**
=> Also, it seems filter at this point is case-sensitive and the filter box is too small for a long text.

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/24596361/5b0c1da0-185c-11e7-8df3-f7ca187f3517.png)

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/24606332/067df5cc-186d-11e7-99c8-9a023fb612e7.png)

**Comment by zmeenakshi** [comment]
1) Increase the length of Term filter text-box. Too small for longer CMQ/SMQ names.
2) State field is cut-off, increase the width of the column.
3) Remove selectbox for level column in Impacted Lists and Non-Impacted lists.
 
![image](https://cloud.githubusercontent.com/assets/25993316/24610434/22971bec-189c-11e7-9f2b-1395aa375176.png)

**Comment by zmeenakshi** [comment]
What happened to extension column?

![image](https://cloud.githubusercontent.com/assets/25993316/24643262/7c9aca9c-192a-11e7-8976-25ea837b4c23.png)

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24743109/9b384ae6-1aca-11e7-800d-72e557c9b64f.png)
