### ISSUE TITLE
All Modules: Disable menu until action is not returned to Home page/main menu.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#177]
The user should not be able to navigate to other modules without closing current form.  The user go to home page/main menu before selecting a different menu bar option.

![image](https://cloud.githubusercontent.com/assets/25993316/24491523/53a2803c-1545-11e7-8761-af40f0c244d6.png)

**Comment by andmiel81** [comment]
clarification needed:
 - Is it safe just to remove the menu from modules sub page, allowing it visible only on the first, home page?
 - If that's not the case, what is the exact use case of the menus?

**Comment by zmeenakshi** [comment]
Currently, user are can navigate to other modules without closing the currently open form. I believe this can cause any issue when multiple user are working on the application.
So, user should close the current form they are in and navigate to home page. Then from the home page select a another module.

**Please skype me if you need clarification.**

**Comment by zmeenakshi** [comment]
Dropped.
