### ISSUE TITLE
Reactivate : When Re-activating a list, there is a success pop=up message, but in fact the list is *NOT* re-activated, and moved back to the left side of the re-activation pane

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#178]
Module: Reactivate/Retire (change to Retire/Reactivate)
Form: Reactivate

When Re-activating a list, there is a success pop-up message, but in fact the list is *NOT* re-activated, and moved back to the left side of the re-activation pane
-----------------------------------------------------------------------
a.	Rule 1: When a parent is selected and the list does not have any child list associated to it, the list is reactivate and displays, “The List is Reactivated successfully.”
Rule 2: When a child is selected and the list has an associated retired parent list, the parent list is also reactivated automatically. Displays a message, "The List and retired parent list is Reactivated successfully"
Rule 3: When a parent list is selected which has associated retired child lists, the child to be reactivated should be selected for reactivation.
If all child lists are not selected (moved to the right box), displays a warning "Not all associate child lists are selected for reactivation. Do you want to continue?" If user selects yes, all selected lists are reactivated. If No, lists are not reactivated.
-------------------------------

**Comment by lsalim** [comment]
Added a commit on that

**Comment by zmeenakshi** [comment]
working as expected:

![image](https://cloud.githubusercontent.com/assets/25993316/24598028/f50758ca-1866-11e7-9519-1f82a9bd462f.png)


![Uploading image.png…]()
