### ISSUE TITLE
Impact Assessment: Scope, category, weight should not be editable for target(right) lists 

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#189]
The Scope, category, weight fields are disabled based on algorithm data. However, Scope, category, weight fields are editable for terms under CMQ/List. These should also be non-editable.

![image](https://cloud.githubusercontent.com/assets/25993316/24602636/4f33d58a-187b-11e7-8e19-0ece78a2f862.png)

**Comment by singhsg** [comment]
These fields are *NOT* editable only when Algorithm=N
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by zmeenakshi** [comment]
It is not possible to add a algorithm condition for the terms which are not directly.

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24642849/f9ba9aa0-1927-11e7-9ceb-bef28a4195b8.png)
