### ISSUE TITLE
Impact Assessment : New PT form. Unable to search or select the list.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#190]
Unable to select the the SOC from the list. Please fix the form so that it easy for user to search and select the term.
Add Selected and Cancel to next to each other. For longer list, the system should display the scroll-bar.

![image](https://cloud.githubusercontent.com/assets/25993316/24603037/e724a9c2-187c-11e7-9b2b-4362bb4e4633.png)

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/24607820/e0b6e3d8-1873-11e7-969e-c33d592cc73e.png)

**Comment by zmeenakshi** [comment]
=>Please make it similar to Hierarchy search. Allow single term search.

=>Also, Hierarchy Search and New PT button should be enabled only  after a CMQ or an SMQ is selected from the Impact Search form.

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24642830/d9dcd52c-1927-11e7-83d0-e816b3cd76aa.png)

**Comment by zmeenakshi** [comment]
Let's add the scroll bar to this pop-up too like hierarchy search.

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24743351/83eafb8a-1acb-11e7-914f-1343fa9ebf28.png)
