### ISSUE TITLE
UI Permissions for User Role

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#192]
A user is anyone not in OPENCQT_ADMIN, OPENCQT_REQUESTOR, or OPENCQT_MQM user group, so basically the default user permissions.

**MQM**
1. Create, Update NMQs/CMQs or other non-NMQ MedDRA Queries. Publish
2. CMQs or other non-NMQ MedDRA Queries from the Update page.
3. Retire and reactivate NMQs/CMQs.
4. Copy CMQs/NMQs/SMQs.
5. Create & Update NMQ/CMQ Relations.
6. Review Requested NMQs.
7. Update SMQ User-defined values.
8. Review & Approve NMQs/SMQs.
9. Publish NMQs/CMQs/SMQs.
10. Perform Impact Assessment.
11. Perform Reporting of NMQs/CMQs/SMQs.
12. Perform Browse & Search for current or pending NMQs/CMQs.
13. View Historic MedDRA Queries
14. View Browse & Search for current NMQs/CMQs.
15. View Versioning Impact Module: View Versioning Impact, View MSSO
16. View  Impact, and Versioning Impact Report

**ADMIN**
(there will be 2 separate admin groups, but we only have one for now, so please just combine these)
1. Add MQ Products, MQ Groups, and NMQ Extensions to the TMS reference code-list.
2. Update CMQs during the MedDRA version upgrade in the Impact Assessment module when a request is submitted.
3. User Management
4. Application Level Configuration Management (if available) -- (e.g. system tuning, threshold, timing, settings, etc.)
5.   List Configuration Management (includes specifying mandatory fields per list types, default attribute values, specifying Pfizer List Extensions, Mapping List Extension to Workflow, managing LOVs, 

1. Add MQ Products, MQ Groups, and NMQ Extensions to the TMS reference code-list.
2. Update CMQs during the MedDRA version upgrade in the Impact Assessment module when a request is submitted.
3.  4. List Configuration Management (includes specifying mandatory fields per list types, default attribute values, specifying Pfizer List Extensions, Mapping List Extension to Workflow, managing LOVs, )

**REQUESTOR**
1. Create, Update NMQs.
2. Create, Update CMQs or other non-NMQ MedDRA Queries. Publish CMQs or other non-NMQ MedDRA Queries from the Update page.
3. Create & Update NMQ/CMQ Relations.
4. Perform Reporting of NMQs/CMQs/SMQs.
5. Perform Browse & Search for current or pending (owned by the Requestor or
6. Designee).
7. Retire or reactivate CMQs
8. View Historic MedDRA Queries
9. View Browse & Search for current NMQs/CMQs.
10. View Versioning Impact Module: View Versioning Impact, View MSSO
11. Impact, and Versioning Impact Report

**USER**
1. Perform Reporting of current NMQs/CMQs/SMQs.
2. View Historic MedDRA Queries
3. View Browse & Search for current NMQs/CMQs.
4. View Versioning Impact Module: View Versioning Impact, View MSSO, Impact, and Versioning Impact Report

ALSO: We want to be able to add/configure different groups from the admin module, so please code with this customization ability in mind(we will add this after basic permission functionality is working)

**Comment by vireshwali** [comment]
done.

**Comment by zmeenakshi** [comment]
COMPLETE
