### ISSUE TITLE
ALL Validation Messages need to be persistent for a CONSISTENT system-wide CONFIGURABLE*time. 

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#197]
Sunil to provide or add the new codelist details.

*ALL* Validation Messages need to be persistent for a *CONSISTENT* system-wide *CONFIGURABLE* time.  This is especially true in all cases where the message is shown for too short a period of time.

**Comment by andmiel81** [comment]
Added a static constant for this purpose to CSMQBean class.
DEFAULT_GROWL_LIFE

**Comment by zmeenakshi** [comment]
How long will be message displayed now? Some error messages are so long that it is still not possible to read the entire message.
Is it possible to display the error message until performs some action (like click somewhere on form).

**Comment by andmiel81** [comment]
current default is 6 sec.
We can make it show until user explicitly close the message box by clicking on the close(&times;)icon on the top right of message.

**Comment by zmeenakshi** [comment]
OK for We can make it show until user explicitly close the message box by clicking on the close(×)icon on the top right of message.

**Comment by andmiel81** [comment]
ok, done this

**Comment by zmeenakshi** [comment]
Don't see any difference.

![image](https://cloud.githubusercontent.com/assets/25993316/24861605/01dbd07a-1e17-11e7-8ca2-72fa7aa6db28.png)

**Comment by zmeenakshi** [comment]
Fix is **ASAP** and update.

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/24907955/f189a51a-1edb-11e7-97e1-b64cc022f8b6.png)

**Comment by andmiel81** [comment]
Normalized error texts throughout the app.

**Comment by zmeenakshi** [comment]
Why would you change to as shown below (screenshot), I specifically asked to maximize the box size and fix the ( x ) issue (not invisible until cursor  in place inside the box) ?

![image](https://cloud.githubusercontent.com/assets/25993316/24945314/583df32e-1f7c-11e7-85c2-e9d95726f455.png)

**Comment by andmiel81** [comment]
The original message was showing full error trace which is absolutely not needed for production version.
And the message length of this "full error trace" is very long, even by maximizing the box, it will fill almost entire screen.

So what I did was normalize the error text as short as possible, while printing detailed error trace to log.

Close icon issue will be fixed shortly

**Comment by andmiel81** [comment]
!! This should be alarmed to all developers !!
Do NOT print full error trace to the frontend, at least for the deploy versions.

**Comment by singhsg** [comment]
Hi, we should have a debug SYSTEM_CONFIG codelist. We need full messages now otherwise it is impossible to debug in the customer environment. When the unit test is completed, it can be shortened.
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by zmeenakshi** [comment]
Please fix this one and make sure message that the error/validation text is consistent across application:

![image](https://cloud.githubusercontent.com/assets/25993316/24992157/792b5a74-203d-11e7-91b5-da443148af4f.png)

**Comment by zmeenakshi** [comment]
Same message is appearing twice:
![image](https://cloud.githubusercontent.com/assets/25993316/25034902/99a7ad00-2107-11e7-92b5-a3f884e91b91.png)

**Can we make sure the entire message fits inside the box?** The red X is taking a lot of space. And, it appears some part of message is cut-off.

![image](https://cloud.githubusercontent.com/assets/25993316/25034952/05e6f930-2108-11e7-8d2c-5179cf682ded.png)

**Comment by zmeenakshi** [comment]
While updating Product in Update and Copy module when I uncheck the previously selected Product the system displays "The Product is required" message before I select the Product from the list, which does not make sense. In fact, during list creation, if I select a wrong product name by mistake and then uncheck it to select the correct Product, I get the same validation message.  The system should give user a chance to update the product and show the  "The Product is required" only if they save the list without adding product to the list.

![image](https://cloud.githubusercontent.com/assets/25993316/25038013/fdc0aa82-2119-11e7-87b6-2c45d80139a1.png)

**Comment by zmeenakshi** [comment]
NOT FIXED:
![image](https://cloud.githubusercontent.com/assets/25993316/25069662/4e58f60c-22a5-11e7-8c9e-19578889e477.png)

FIXED:
![image](https://cloud.githubusercontent.com/assets/25993316/25069660/2d6a5bac-22a5-11e7-8506-3f13d421dfbe.png)

While updating Product in Update and Copy module when I uncheck the previously selected Product the system displays "The Product is required" message before I select the Product from the list, which does not make sense. In fact, during list creation, if I select a wrong product name by mistake and then uncheck it to select the correct Product, I get the same validation message. The system should give user a chance to update the product and show the "The Product is required" only if they save the list without adding product to the list.

**Comment by andmiel81** [comment]
- Reduced Message Icon space
- Fixed Duplicated text for "Required" validation error
- Product selection issue was already fixed in previous commit.
