### ISSUE TITLE
Browse and Search -> Relations: Provide an indication of which child lists are *INACTIVE* in Browse&Search and Update

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#199]
Module: Browse and Search 
Form: Relations

1) Add letter 'I' in red colour next to the list name if an associated child lists inactive (CMQ_STATUS='I').

2) Remove these check-boxes.
![image](https://cloud.githubusercontent.com/assets/25993316/24662645/4fc9af9e-1973-11e7-8fab-c15a7563a4b0.png)

**Comment by zmeenakshi** [comment]
1) Letter I is not appearing in front of the Inactive list name in relations form.

2) Check-boxes have not been removed.

![image](https://cloud.githubusercontent.com/assets/25993316/24707779/87f7d390-1a32-11e7-967b-ab0e0271e43b.png)

![image](https://cloud.githubusercontent.com/assets/25993316/24707810/9d2b37a2-1a32-11e7-9dae-fd619d2d2edd.png)

**Comment by zmeenakshi** [comment]
I can't verify the fix.  Next time onward add screenshot of the fix to the ticket.

The search is not showing the list shown in the above screenshot. In fact, search has a problem. You **must** perform basic test before committing fixes.

![image](https://cloud.githubusercontent.com/assets/25993316/24739367/3ad7ebe0-1ab9-11e7-93ad-4b3193d23772.png)

![image](https://cloud.githubusercontent.com/assets/25993316/24739397/60ccaf48-1ab9-11e7-8815-06cd75d64fdc.png)

**Comment by andmiel81** [comment]
![Uploading image.png…]()
![image](https://cloud.githubusercontent.com/assets/22034392/24741240/6962e078-1aa5-11e7-860c-8b134f341c72.png)

This is weird, because I don't see the errors on my copy.

**Comment by zmeenakshi** [comment]
=> I'm was somehow able see the letter I after list name. I' m OK with adding it after list name if it is not possible to add before the list name. But, it is too close to the list name, almost overlapping.

![image](https://cloud.githubusercontent.com/assets/25993316/24742969/0e1c941e-1aca-11e7-947a-8b82f5c2713f.png)

**Comment by zmeenakshi** [comment]
Also, can you expand the width of the first column. We can reduce Code, Level, Scope, Category, (Weight will not be more than 2 characters)and Delete.

As we are adding "I" after list name the user will not be able to see if the list name is long until they expand the width of list name.

**Comment by zmeenakshi** [comment]
The letter **I** is still overlapping Browse & Search-> Relations:
![image](https://cloud.githubusercontent.com/assets/25993316/24874819/9a114c18-1e43-11e7-89a9-e59fa92c2107.png)


**To make UI consistent** : Please expand the width of the first column and reduce Code, Level, Scope, Category, (Weight will not be more than 2 characters)and Delete in Create, Copy and Update in Relations.

** Inactive indicator (letter I) is appearing correctly in Update ->Relations **
![image](https://cloud.githubusercontent.com/assets/25993316/24874900/ce7332a0-1e43-11e7-94df-ede57d5dcfdd.png)

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/24878954/6cd4f424-1e35-11e7-821e-ede20390e577.png)
![image](https://cloud.githubusercontent.com/assets/22034392/24879014/a7c4a37c-1e35-11e7-8b9c-9e2e9d6f18f2.png)
