### ISSUE TITLE
Administrator : Editing codelist is showing "save confirmation" in the UI while changes are NOT saved.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#208]
Issue: Codelist changes are NOT saved the DB. 

To reproduce the issue, edit more than one codelist values for a same codelist type, and do same for different codelists. As, at time it works correctly the first codelist update.

The Active Flag is checked-on:
![image](https://cloud.githubusercontent.com/assets/25993316/24744825/f28ce0ee-1ad0-11e7-8873-875f158404ff.png)

Change the active flag to 'N':
![image](https://cloud.githubusercontent.com/assets/25993316/24744855/0e1bb1be-1ad1-11e7-9e7e-38193210a259.png)

The save confirmation is displayed, but the active flag is till 'Y'
![image](https://cloud.githubusercontent.com/assets/25993316/24744910/4b474634-1ad1-11e7-85cf-b9abdbb6b2f4.png)

**Comment by zmeenakshi** [comment]
I changed serial# for DME to 1 which changed the serial# of TME 0 (which is incorrect, it should change to 0). Further, when I changed serial # of TME to 1 the system showed the changes saved, however, the serial # remained 0 for TME.

The codelist values are not re-sequenced correctly.

![image](https://cloud.githubusercontent.com/assets/25993316/24838963/a3cf70b0-1d6f-11e7-941f-9a17708c2dc9.png)

**Comment by andmiel81** [comment]
please check this

**Comment by zmeenakshi** [comment]
No change.

![image](https://cloud.githubusercontent.com/assets/25993316/24861066/fb30cd5e-1e14-11e7-8ba6-2fcc43dd3fc8.png)

**Comment by zmeenakshi** [comment]
Other issues related to codelist are resolved.
The system should NOT allow user to enter serial # 0 or less than 0.
![image](https://cloud.githubusercontent.com/assets/25993316/24895343/89d7db0e-1ead-11e7-8831-7f035dd419bc.png)

**Comment by zmeenakshi** [comment]
Fixed.
