### ISSUE TITLE
All Modules : Detail and Search: Can type-ahead be enabled for Product list even though multi-select is enabled?  

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#216]

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/24881252/88abbff4-1e3d-11e7-94cc-d9d80fb3062e.png)
I have added filterbox (screenshot above) for products select.

**Comment by zmeenakshi** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/25993316/24907105/5ec2ecda-1ed8-11e7-968c-7edea616ed0b.png)

**Comment by zmeenakshi** [comment]
Fix Copy module:

![image](https://cloud.githubusercontent.com/assets/25993316/24941367/89be5f8e-1f67-11e7-8bb6-0cfed05a14e6.png)

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/24945550/5ad977d8-1f7d-11e7-8ebe-c5f334f224bc.png)
