### ISSUE TITLE
Copy/Update/Browse & Search -> Search and Details form : Same Product name is appearing twice.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#226]
The same product is appearing twice in the Search and Details page.

![image](https://cloud.githubusercontent.com/assets/25993316/24969047/0ecfdb20-1fcd-11e7-901f-d2b6068ac3a5.png)

![image](https://cloud.githubusercontent.com/assets/25993316/24969102/33f7f22a-1fcd-11e7-9717-a09c3aabebf4.png)

**Comment by andmiel81** [comment]
I think there are some duplicates on db.
And newly created lists doesn't show such issues.

An algorithm has been applied to remove duplicacy from UI side.

**Comment by zmeenakshi** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/25034814/f1abafca-2106-11e7-9cff-cfa39bd3cf83.png)

![image](https://cloud.githubusercontent.com/assets/25993316/25034831/12deb3ae-2107-11e7-915e-b15705a58ff1.png)
