### ISSUE TITLE
Confirm: Workflow buttons are NOT working correctly.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#231]
REVIEWED button is enabled when STATE is REVIEWED, which is NOT correct. I can demote or approve the list, moreover, delete button is enabled.

![image](https://cloud.githubusercontent.com/assets/25993316/24992621/130f4a0e-2040-11e7-8f1a-11386dacf862.png)

REVIEWED button in enabled when CMQ_STATE = 'DRAFT'
DELETE button is enabled when CMQ_STATE = 'DRAFT' AND last activation date is null
DEMOTE TO DRAFT button is enabled when CMQ_STATE = 'REVIEWED' OR CMQ_STATE = 'APPROVED'
APPROVED button is enabled when CMQ_STATE = 'REVIEWED'

**Comment by andmiel81** [comment]
Data was being saved correctly, but the UI wasn't being updated according to the data after clicking on the button.

Fixed now.

**Comment by zmeenakshi** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/25993316/25007393/fd5b7ee2-207d-11e7-8a80-b87bb9517556.png)
