### ISSUE TITLE
Change Header and Login Info

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#234]
Page: CSMQ

1) Only include groups RELEVANT to CQT(ie the user role, OPENCQT_ADMIN in this case)
2) Not show OPENCQT_ADMIN, but just show "ADMIN"
3) Move these fields to a horizontal navbar of some sort at the top of the page, instead of taking up a lot of room at the header
4) Also not show username, just Last, First
5) get rid of the buttons except logoff
And have all this horizontally arranged in a navbar at the top
Just a transparent bar that contains that info/that button

![image](https://cloud.githubusercontent.com/assets/12534580/25008583/2ee36d90-2032-11e7-9621-1dee9555470f.png)

**Comment by andmiel81** [comment]
This has been updated.
Please check and confirm
