### ISSUE TITLE
Reports- > MedDRA Versioning Reports

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#237]
Codelist for reports:
![image](https://cloud.githubusercontent.com/assets/25993316/25037251/af8e44f4-2115-11e7-8e40-e4be299c9fc6.png)

The user should be able to generate the report (in excel format) stored in the application at the location mentioned in codelist (MEDDRA_IMPACT_DL_PATH).
Also, as and when a new report is added, the user should see the new report in the drop-down and if any report is removed that should not appear in --select a report-- drop-down.

![image](https://cloud.githubusercontent.com/assets/25993316/25037289/f60fe996-2115-11e7-8c75-a261bc9435e0.png)

**Comment by andmiel81** [comment]
Please give more details about Meddra Versioning Reports.

**Comment by zmeenakshi** [comment]
What else do you need?

![image](https://cloud.githubusercontent.com/assets/25993316/25062088/a58ba136-21e2-11e7-81a3-6c92ab39e882.png)

**Comment by zmeenakshi** [comment]
ADDED.
