### ISSUE TITLE
All Module: Created by : Replacle |#| with space comma space for now.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#240]
Issues:
1) All Module: Created by : Replacle |#| with space comma space for now.
![image](https://cloud.githubusercontent.com/assets/25993316/25069923/76c1e9bc-22ac-11e7-88da-db30a1acc62e.png)

2) Not sure why Last modified by and last modification date column are populated during list creation.
![image](https://cloud.githubusercontent.com/assets/25993316/25069928/9e3d0ab2-22ac-11e7-81e5-c0c6cbf48271.png)

**Comment by andmiel81** [comment]
updated
