### ISSUE TITLE
Create Module: Add Details tab doesn't show Product on saving List.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#241]
Create Module:
Product is selected while creating List, however, once list is saved product information is no longer available on Add Details tab. Though, System shows the message "List is successfully saved" and product can be seen on Confirm tab.

![image](https://cloud.githubusercontent.com/assets/26054860/25087994/8e86e784-2390-11e7-98a1-eb77ea86e5c6.png)

-Ashleen

**Comment by zmeenakshi** [comment]
Issue has been fixed:
![image](https://cloud.githubusercontent.com/assets/25993316/25090848/4327a8ce-23a3-11e7-8d0f-e3c6171a31cf.png)
