### ISSUE TITLE
Focus moves to the back screen instead of Next screen on form cancellation.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#243]
Create Module:
Focus moves to the back screen instead of Next screen on form cancellation when user click No to the message "There are some unsaved change. Do you want to continue?"

Steps to reproduce:
•	Added Relations 
•	Clicked Next
•	Warning Message "There are some unsaved change. Do you want to continue?"
•	Clicked No.
•	Form Cancelled message displays and focus goes to Informative Notes Tab

-Ashleen Kaur

**Comment by andmiel81** [comment]
I think this is as it was requested.

Please confirm the process:

When there are changes that are not saved and user clicks on tab or next button, a confirm dialog shows saying "There are some unsaved change. Do you want to continue?".
 - when user clicks on "Yes", it will save the changes and move to the next or clicked tab.
 - when user clicks on "No",
   currently it will cancel the changes and move to the next or clicked tab.
   How should it be corrected?

**Comment by zmeenakshi** [comment]
As per the tester:
The focus shifted from Relations form to Informative Notes form on click NO for the Next button confirmation message.

**Comment by CQTdev** [comment]
Issue no longer exists. Hence, closing the ticket.

-Ashleen
