### ISSUE TITLE
Created By: user name not appearing in correct form on Add Details tab, Confirm tab and in MQ Detailed Report

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#244]
'Created By' user is not appearing correctly on Add Details, Confirm tab and MQ Detailed Report 

For example: Initial Creation By: |#|ZUTSHM-Dummy|#|MEENAKSHI|#|ZUTSHI|#|MANAGER[OPENCQT_MQM]|#|

![image](https://cloud.githubusercontent.com/assets/26054860/25089121/ebeea864-2398-11e7-9102-8f177242109c.png)

**Comment by zmeenakshi** [comment]
Not an issue.
