### ISSUE TITLE
Issues related to PXED

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#245]
*NONE is appearing for Activation By. *
![image](https://cloud.githubusercontent.com/assets/25993316/25090972/0f2d7cfa-23a4-11e7-828e-b1c4b641ed34.png)

*Publish module should not appear if AD group REQUESTOR. *
![image](https://cloud.githubusercontent.com/assets/25993316/25090957/02e49b18-23a4-11e7-9a91-6d22646ed7b2.png)

**Comment by vireshwali** [comment]
done.

**Comment by zmeenakshi** [comment]
2) FIXED:
![image](https://cloud.githubusercontent.com/assets/25993316/25194376/e5111c82-2557-11e7-8143-0783c88681ca.png)


![image](https://cloud.githubusercontent.com/assets/25993316/25194408/f7b99224-2557-11e7-98f2-61cf5a3e21ea.png)


1) FIXED
![image](https://cloud.githubusercontent.com/assets/25993316/25194526/48984a6e-2558-11e7-9b54-8fd45b889763.png)
