### ISSUE TITLE
Create/Copy/Update -> Confirm: If Lists is Approved once, the user should not be able to delete the list. The Delete button should be disabled.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#247]
If Lists is Approved once, the user should not be able to delete the list. The Delete button should be disabled.

Condition of CMQ_BASE_CURRENT_AUDIT: CMQ_STATE_OLD field.
If CMQ_STATE_OLD='APPROVED' the selected list, disable delete button.

**Comment by andmiel81** [comment]
I don't see any Entity is created for CMQ_BASE_CURRENT_AUDIT table.
Please ask someone who is responsible for data structure and business logic, to create entity & relationships code for the Audit table.

**Comment by andmiel81** [comment]
Check this and let me know the status, please.

**Comment by ashleenkaur** [comment]
Fixed in Pfizer.
