### ISSUE TITLE
Error in Admin Tab in Customer Environment

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#248]
JBWEB000070: exception

javax.servlet.ServletException: Error Parsing /admin/programTable.xhtml: Error Traced[line: 74] Attribute "value" was already specified for element "p:inputText".
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	com.dbms.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:61)
JBWEB000071: root cause

javax.faces.view.facelets.FaceletException: Error Parsing /admin/programTable.xhtml: Error Traced[line: 74] Attribute "value" was already specified for element "p:inputText".
	com.sun.faces.facelets.compiler.SAXCompiler.doCompile(SAXCompiler.java:466)
	com.sun.faces.facelets.compiler.SAXCompiler.doCompile(SAXCompiler.java:440)
	com.sun.faces.facelets.compiler.Compiler.compile(Compiler.java:124)
	com.sun.faces.facelets.impl.DefaultFaceletFactory.createFacelet(DefaultFaceletFactory.java:481)
	com.sun.faces.facelets.impl.DefaultFaceletFactory.access$100(DefaultFaceletFactory.java:106)
	com.sun.faces.facelets.impl.DefaultFaceletFactory$1.newInstance(DefaultFaceletFactory.java:199)
	com.sun.faces.facelets.impl.DefaultFaceletFactory$1.newInstance(DefaultFaceletFactory.java:197)
	com.sun.faces.facelets.impl.DefaultFaceletCache$1.newInstance(DefaultFaceletCache.java:86)
	com.sun.faces.facelets.impl.DefaultFaceletCache$1.newInstance(DefaultFaceletCache.java:81)
	com.sun.faces.util.ExpiringConcurrentCache$1.call(ExpiringConcurrentCache.java:99)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	com.sun.faces.util.ExpiringConcurrentCache.get(ExpiringConcurrentCache.java:114)
	com.sun.faces.facelets.impl.DefaultFaceletCache.getFacelet(DefaultFaceletCache.java:124)
	com.sun.faces.facelets.impl.DefaultFaceletCache.getFacelet(DefaultFaceletCache.java:63)
	com.sun.faces.facelets.impl.DefaultFaceletFactory.getFacelet(DefaultFaceletFactory.java:295)
	com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:370)
	com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350)
	com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199)
	com.sun.faces.facelets.tag.ui.IncludeHandler.apply(IncludeHandler.java:124)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	com.sun.faces.facelets.tag.ui.DefineHandler.applyDefinition(DefineHandler.java:106)
	com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:206)
	com.sun.faces.facelets.impl.DefaultFaceletContext$TemplateManager.apply(DefaultFaceletContext.java:395)
	com.sun.faces.facelets.impl.DefaultFaceletContext.includeDefinition(DefaultFaceletContext.java:366)
	com.sun.faces.facelets.tag.ui.InsertHandler.apply(InsertHandler.java:111)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137)
	com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202)
	javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120)
	javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95)
	com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312)
	com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371)
	com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350)
	com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199)
	com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:174)
	com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161)
	com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1006)
	com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99)
	com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	com.dbms.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:61)

**Comment by lsalim** [comment]
I have added a commit to fix it.
