### ISSUE TITLE
Copy module: Details: Error is the screenshot is displayed when product name is not changed while created a list in copy module.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#250]
When creating list from an existing list is copy module if the product name is not changed the following error is created.
If user changes the Product name then they can save record without any error.

![image](https://cloud.githubusercontent.com/assets/25993316/25098680/1a390f56-23c7-11e7-9f10-3612cc26a2c3.png)

**Comment by vireshwali** [comment]
done. someone had changed the code for products in copy.

**Comment by zmeenakshi** [comment]
Fixed.
