### ISSUE TITLE
Impact Assessment : Increase the width of Code column in the right panel.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#253]
Module: Impact Assessment

**Note: Please make sure no data is cut-off from the display.
Also, can we make the columns in both panel expandable.

![image](https://cloud.githubusercontent.com/assets/25993316/25173799/188b086a-2513-11e7-8491-8d22678b4452.png)

**Comment by andmiel81** [comment]
Controlling column width when using multi-row, colspanned header in the table, is impossible with current version of primefaces.
Only the first column(term name) will be available for dynamic resizing. and the rest of the columns will divide the remaining space evenly.

**Comment by zmeenakshi** [comment]
Oh right, you told me this before.
Please increase the width of column so that data is not cut-off.

**Comment by zmeenakshi** [comment]
FIXED:
![image](https://cloud.githubusercontent.com/assets/25993316/25312107/3fb02bf0-282e-11e7-953a-98eb0ef6bc97.png)
