### ISSUE TITLE
IA and View Current Version Impact - Legend.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#254]
Impact Legend

When resizing legend window, only external frame is expanded. The text part of the window remains fixed:

![image](https://cloud.githubusercontent.com/assets/25993316/25176700/b600e304-251c-11e7-87e4-3a1e9beac1f9.png)

**Comment by andmiel81** [comment]
I am making this dialog NOT RESIZABLE, since there's no point to make it resizable.

**Comment by zmeenakshi** [comment]
Then make this pop-up bigger and increase the font size.

**Comment by zmeenakshi** [comment]
Hi, Can you add a screenshot here? This update is no deployed yet.

**Comment by zmeenakshi** [comment]
Fixed.
