### ISSUE TITLE
Impact Assessment : List expands automatically

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#258]
The list once expanded although collapse, expand automatically.

![image](https://cloud.githubusercontent.com/assets/25993316/25222957/8bcc3186-25d7-11e7-9b57-21b86798f961.png)

**Comment by andmiel81** [comment]
Actually, this is the default behavior of Primefaces' treetable component, and there's nothing we can do to control it.

**Comment by zmeenakshi** [comment]
Fixed.
