### ISSUE TITLE
Disable drag 'n' drop feature from Hierarchy Search window (All modules). 

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#259]
Disable drag 'n' drop feature from Hierarchy Search window (All modules) since it is inconsistent and displays message "The relation already exists" even when relation is not there.

![image](https://cloud.githubusercontent.com/assets/26054860/25224734/e6f0160e-25dc-11e7-8795-c34e073df8e7.png)

-Ashleen

**Comment by andmiel81** [comment]
I am not sure if I have to remove this feature completely or you just ment to have it fixed.
Anyway, now, I have fixed a few bugs and error messages.
Please take a look and let me know if it is still a subject to deletion.

**Comment by zmeenakshi** [comment]
Fixed to display correct message when No term/relation is selected:
![image](https://cloud.githubusercontent.com/assets/25993316/25311853/e5a284a0-2828-11e7-98e5-b1dd9f1f8f6d.png)

**Comment by zmeenakshi** [comment]
ISSUE: 
1) When user drag 'n' drop the *same term* from a *different LEVEL*, the system does not add the term instead displays an message:
![image](https://cloud.githubusercontent.com/assets/25993316/25311948/92249b22-282a-11e7-909f-2c87c2bd4133.png)

2) When user drag 'n' drop the *same term* from a *same LEVEL*, the systemdisplays an incorrect message:
![image](https://cloud.githubusercontent.com/assets/25993316/25311960/bd4bb3b2-282a-11e7-845c-3cec02990dd1.png)

**Comment by andmiel81** [comment]
I guess this is due to wrong mouse move.

The nodes from HS dialog should be marked blue when selected correctly.
like this screenshot:
![image](https://cloud.githubusercontent.com/assets/22034392/25312219/f95c30fa-2813-11e7-852c-90622428c3b8.png)
