### ISSUE TITLE
Modules: UPDATE/COPY/BROWSE & SEARCH - Created By: NONE in search results

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#261]
Modules: UPDATE/COPY/BROWSE & SEARCH 
Created By  is displayed as NONE in search results.

**Comment by zmeenakshi** [comment]
Create by user is: 
![image](https://cloud.githubusercontent.com/assets/25993316/25285724/df2a42c6-26d8-11e7-9306-43ae98ff27cf.png)

But in the search grid is showing NONE:
![image](https://cloud.githubusercontent.com/assets/25993316/25285788/174a70e0-26d9-11e7-88f4-debe0008b92f.png)

**Comment by zmeenakshi** [comment]
FIXED:
![image](https://cloud.githubusercontent.com/assets/25993316/25311812/f69d2dce-2827-11e7-833b-db05dba7ce27.png)
