### ISSUE TITLE
Enhance the format of PDF List Details Report.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#270]
Hello Team,

Please make PDF format look enhanced by:
1. By adding uniform space between Report Generation time and Total count 
2. Adding space between Total count and table.
3. correct the alignment of column headings (like Status and Algorithm are not correctly aligned)
4. Decrease the column width of Name, Extension and Group and increase the Column width of Product.

![image](https://cloud.githubusercontent.com/assets/26054860/25332159/218f4af4-2903-11e7-87c4-e907d872f83b.png)

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/25400621/729d2218-29f3-11e7-8598-b75717888495.png)

**Comment by CQTdev** [comment]
Status and Algorithm are not aligned

![image](https://cloud.githubusercontent.com/assets/26054860/25428523/bdeb9a06-2a93-11e7-90bb-c82e5c81f45d.png)

**Comment by andmiel81** [comment]
It seems that the server's report template is old.
Please test it again after refreshing server's report templates

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/25445869/e269fe4c-2aaf-11e7-8a7a-9f9224089274.png)
fixed on 8888

**Comment by CQTdev** [comment]
Resolved.
