### ISSUE TITLE
Update module: Updating extension removes values from Drug Program, Protocol and Product.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#276]
Updating extension removes values from Drug Program, Protocol and Product. 

Steps to reproduce:
1. Create TME list.
2. From Update module, update the extension from TME to PROTOCOL. 
3. Observe that the drug program, protocol and product fields becomes blank. 

Below 2 screenshots are showing the comparison:

![image](https://cloud.githubusercontent.com/assets/26054860/25347439/9059383e-2938-11e7-91d8-d4bb9d1018de.png)

![image](https://cloud.githubusercontent.com/assets/26054860/25347443/973d7b10-2938-11e7-84ca-0f4209e792a1.png)

**Comment by zmeenakshi** [comment]
This is an expected behaviour
