### ISSUE TITLE
Module: Update: For users who are assign AD group REQUESTOR they should be able to update ONLY those CMQ that are created by them or assigned to them (they are Designee)

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#283]
Module: Update

For users who are assigned AD group REQUESTOR they should be able to update ONLY those Lists or CMQs which are created by them or assigned to them (they are Designee).

**Comment by andmiel81** [comment]
This can't be completed at the moment, because we have no method to match user-ids on designees with the logged-in user.

**Comment by zmeenakshi** [comment]
Can you check with Alexander on this?

**Comment by zmeenakshi** [comment]
Andrew, There is a need for a for group specific condition to allow data updates.  Right now they can not do this.  The reason appears to be: there is no method to match user-ids on designees with the logged-in user.

**Comment by zmeenakshi** [comment]
The user group other than MQM should be able to search for ONLY ACTIVE or those list for which they have been added as a Designee
DO this for update/copy/browse & search -> Search

**Comment by zmeenakshi** [comment]
=> The user who are assigned as a designee to the list, should be able to review and approve the list.

**Comment by zmeenakshi** [comment]
=> The users group(REQUESTOR and ADMIN) other than MQM (role OPENCQT_MQM) should be able to SEARCH and UPDATE ONLY ACTIVE list or those list for which they have been added as a Designee. This is applicable on following modules: Update/Copy/Browse & Search, IA and View Version Impact.

=> Since users who belong to EVERYONE group only have browse access, so they should not be able to update any data in any of the modules. They will be able to search only for ACTIVE lists.
In fact, for user group EVERYONE defaults should be status='ACTIVE' and state='PUBLISHED' and these two fields should be DISABLED (that means, EVERYONE user should not be able to select other states or status from the drop-down) in the search form.

=> The user who are assigned as a designee to the list, should be able to review and approve the list.
NOTE: Please check with Alexander about the correct Pfizer group names and database roles.

**Comment by zmeenakshi** [comment]
Added a new condition (fixed by Leyla on 5th May)
=> MQM and REQUESTOR should be able to Create a new list.

TEST: The all conditions mentioned in this ticket.

**Comment by zmeenakshi** [comment]
The user (REQUESTOR) should be able to update on when following conditions are true
1) They are designee or they have created the list
2) The list's status is P
3) List's state is DRAFT or REVIEWED
All, these should be true for REQUESTOR to edit a list.

The user (MQM) should be able to update on when following conditions are true
1) MQM can edit every list.
2) They can promote list from one workflow level to another.

The user (ADMIN) should be able to update on when following conditions are true
1) They are designee
2) The list's status is P
3) List's state is PENDING IA and REVIWED IA.
All, these should be true for ADMIN to edit a list.

**Comment by ashleenkaur** [comment]
Fixed. Tested in Pfizer CQT2.
