### ISSUE TITLE
Hierarchy Search : Primary Path.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#285]
**Angioedema** :
![image](https://cloud.githubusercontent.com/assets/25993316/25431371/f9cdc3f0-2a9d-11e7-8395-f1882b1dfb67.png)

Current from MedDRA Browser:
![image](https://cloud.githubusercontent.com/assets/25993316/25431774/99148f38-2a9f-11e7-8fda-a4b4ac09de42.png)

Target from MedDRA Browser:
![image](https://cloud.githubusercontent.com/assets/25993316/25431886/0903c188-2aa0-11e7-8693-bcf839696c6f.png)
==============================================================
DIABETES MELLITUS in both Current and Target is same:
![image](https://cloud.githubusercontent.com/assets/25993316/25431378/0564d2c6-2a9e-11e7-8c85-026073e7e00f.png)

![image](https://cloud.githubusercontent.com/assets/25993316/25431678/347507ec-2a9f-11e7-98d0-733be1c1ace0.png)
===============================================================

ANGIOEDEMA LARYNX: Target (is not showing Primary Path)
![image](https://cloud.githubusercontent.com/assets/25993316/25432710/2722945c-2aa3-11e7-8164-8cc12bb3574e.png)

MedDRA Browser: Primary Path (Target)
![image](https://cloud.githubusercontent.com/assets/25993316/25432786/79053a18-2aa3-11e7-871e-c702d7415a79.png)

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/25770402/00abb220-3252-11e7-811c-71dc9799007a.png)

![image](https://cloud.githubusercontent.com/assets/25993316/25770412/42f93382-3252-11e7-84a4-d9f6a2c887be.png)

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/25770417/899508d4-3252-11e7-97f8-75a36ed0d13d.png)

**Comment by zmeenakshi** [comment]
Commit done. To be tested when code is redeployed.

**Comment by zmeenakshi** [comment]
Fixed:
Colour code has been removed. Instead Show Primary Path check box is add to the HS window.
On Clicking Show Primary Path, only primary path is displayed for the term:
![image](https://cloud.githubusercontent.com/assets/25993316/25778874/a56a9598-3328-11e7-92b8-f369bfdf8d84.png)

both Primary and Secondary Path:
![image](https://cloud.githubusercontent.com/assets/25993316/25778871/8f73a162-3328-11e7-976f-7d2c67bf2f5b.png)

**Comment by CQTdev** [comment]
Tested. Issues is fixed.
