### ISSUE TITLE
Dictionary Version/Name Field are Both Blank

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#29]
Module: Browse & Search/ Update /Copy
Form: Details
The dictionary version and name fields are blank. Should pick the value from the codelist.

**Comment by acoughlin** [comment]
dictionary version and name is displayed only when list is saved in the Create module.

**Comment by vireshwali** [comment]
fixed. name hardcoded to meddra since no value in codelist for name yet and version comes from config codelist table.
