### ISSUE TITLE
Reactivate module: mistake in Confirm Reactivation window name and error message.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#292]
Reactivate/Retire module: 'Confirm Reactivation' window name is wrongly displayed as 'Confirm Promotion'.

Steps to reproduce:
Select any list, move to the right box and click on Reactivate button.

![image](https://cloud.githubusercontent.com/assets/26054860/25585430/22f2e9d6-2eb8-11e7-9b3b-2ba5738f3a5b.png)

**Comment by CQTdev** [comment]
Error message is wrongly displayed as "The list being promoted has an associated list that must be Promoted" instead of "The List being reactivated has an associated list that must be reactivated."
Reactivation follows same rules as Publish. Only group (Parent and Child) Reactivation is allowed. 

![image](https://cloud.githubusercontent.com/assets/26054860/25586627/c4bb3dea-2ebd-11e7-87ca-035f4d056936.png)

**Comment by andmiel81** [comment]
I think this issue has been already handled by @lsalim on commit 1697779b512b8b208f9a9d7bd705c167a4d04afb and 99b38a1b1d4cecc41df4843a1de40cb5fa80e3bb

**Comment by CQTdev** [comment]
Resolved.
