### ISSUE TITLE
How can the resize be made better to use the BOTTOM of the screen for all forms? 

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#294]
The issues appears on the Pfizer PCs. The whole problem is we don't have dynamic sizing based on the user's resolution.

**Comment by CQTdev** [comment]
IA module: There is another problem with resizing on DBMS environment. If Impact Search window is maximized to an extent where the window name hides, it can not be seen again even on resizing the window:

![image](https://cloud.githubusercontent.com/assets/26054860/25791425/d70860ac-33dd-11e7-9499-74202eaf9e9d.png)

**Comment by zmeenakshi** [comment]
Fixed.
