### ISSUE TITLE
All Modules : Parent List. Showing duplicate record for child list.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#296]
1) Replace **Level** with **Extension**: 
2) The same PRO list is displayed twice in the Parent List pop-up window.

![image](https://cloud.githubusercontent.com/assets/25993316/25613756/ff0c9b12-2f4c-11e7-8609-3fea5fad6051.png)

**Comment by CQTdev** [comment]
'Level' is replaced by 'Extension' but it is still displaying 1. Valid Extensions for this application are TME, TR1, PRO, CPT and DME.
The same PRO list is displayed twice in the Parent List pop-up window

![image](https://cloud.githubusercontent.com/assets/26054860/25673111/ebe3f53c-3053-11e7-9dbf-760753111f39.png)

**Comment by CQTdev** [comment]
Issue Fixed:

![image](https://cloud.githubusercontent.com/assets/26054860/25838096/f3d187aa-34ae-11e7-92ed-71d19c462736.png)
