### ISSUE TITLE
POST GO-LIVE: Update -> Update Details in Form 'Audit_testing_TME' , duplicate records inserted in Audit table for repeated save action

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#297]
When updating data in Module **Update Details** in Form **Audit_testing_TME**, if the users clicks on the save button multiple times without changing any data, duplicate audit records are insert in Table - **cmq_base_current_audit**

![image](https://cloud.githubusercontent.com/assets/16257105/25626300/bb9277f0-2f7c-11e7-8d7f-9226ce8266b6.png)

**Comment by zmeenakshi** [comment]
Fixed.
