### ISSUE TITLE
Minor UI issues.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#298]
Make the type-ahead on all UI form consistent with Impact Search: Administration-> Configuration Codelist.
The type-ahead for Impact search works when userr hits ENTER key. 

Replace Term with List in Impact Search window in Impact Assessment and View Version Impacts:
![image](https://cloud.githubusercontent.com/assets/25993316/25649802/2cdce278-2ff6-11e7-924c-d6503819ac1a.png)

**Comment by zmeenakshi** [comment]
**ISSUE 1**
1) Please replace Term with **SMQ Name** in Impacted SMQs and Non-Impacted SMQ.
2) Replace Term with **List Name** in the Impacted Lists and Non-Impacted Lists.
3) Why is there a sort on List column? Please remove it.
4) Add type-ahead for code column.
5) For all type-ahead, the system should start loading search result as user stops typing. All Impact Search Tab and Administration Codelist Forms.

![image](https://cloud.githubusercontent.com/assets/25993316/25669154/54721be6-3046-11e7-8ecf-84886a0d6183.png)

**Comment by zmeenakshi** [comment]
=> Status type-ahead is not working.

=> Add a type-ahead from State column in Impacted List and Non-Impacted List tabs:
![image](https://cloud.githubusercontent.com/assets/25993316/25706525/506d366c-30fe-11e7-962b-1f47d258ec73.png)

**Comment by CQTdev** [comment]
Code Type ahead is not working. 

![image](https://cloud.githubusercontent.com/assets/26054860/25847735/ee4d73f4-34d4-11e7-9e91-6b4c6a6ffa38.png)

**Comment by CQTdev** [comment]
Fixed in Pfizer.
