### ISSUE TITLE
Post Reactivation, 'Last Activation By' is displayed as NONE.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#301]
Post Reactivation, Last Activation By is displayed as NONE.
Steps to reproduce.
1. Create list
2. Review -> Approve->Publish
3. Observe on Browse & Search and Update module, Last Activation Date and Last Activation By information is available.
4. Now Retire and then Reactivate the list
5. Observe that the Last Activation Date is available but Last Activation By is NONE.

![image](https://cloud.githubusercontent.com/assets/26054860/25672267/761f16d6-3050-11e7-9115-82e00696f182.png)

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/25757058/aa7c0aaa-31e6-11e7-927e-c5f8aafdec7d.png)
