### ISSUE TITLE
All Modules : Hierarchy Search : Add Show Primary path check-box for in Current and Target Hierarchy Search window to return only primary path terms.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#303]
All Modules
Form: Hierarchy Search

Add a Show Primary path check-box for in Current and Target Hierarchy Search window to return only primary path terms.

**Comment by zmeenakshi** [comment]
![image](https://cloud.githubusercontent.com/assets/25993316/25770419/9be2f898-3252-11e7-9aa4-cb2d0721256a.png)

![image](https://cloud.githubusercontent.com/assets/25993316/25770422/a847118c-3252-11e7-9b9e-bb70c7272882.png)

==========================

![image](https://cloud.githubusercontent.com/assets/25993316/25770427/bd4ed51a-3252-11e7-8f12-46ed9eb30040.png)

![image](https://cloud.githubusercontent.com/assets/25993316/25770428/c9bb931a-3252-11e7-9c0c-8416a90af922.png)

**Comment by CQTdev** [comment]
Tested. Issue fixed.
