### ISSUE TITLE
Impact Assessment : New Rules for Publish.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#310]
Publish Future Version: 
1) Left box: will display TARGET LISTS where state is 'APPROVED IA' and status is 'P'
2) If level 1 list does not have any associated child, then Promote button will execute rule 1. Also, display the pre-confirmation message/panel.
Rule 1:  Change the TARGET.STATE='PUBLISHED IA' and TARGET.STATUS=’P’. Display the message, "The List is Published successfully."  
2) If level 2 or level 1 have an associated parent/child list and both are not selected, then Promote button will execute rule 2.
Rule 2: Display the warning message, "The List being promoted has an associated list that must be promoted." and do nothing.
3) If level 2 or level 1 have any associated child and both selected, then Promote button will execute rule 3. Also, display the pre-confirmation message/panel.
Rule 3: Change the state of both lists to TARGET.STATE='PUBLISHED IA' and TARGET.STATUS=’P’. Display the message "The List(s) are Published successfully."

**NOTE** : Comment out the old code don't remove it and disable Demote to Draft tab.

**Comment by CQTdev** [comment]
Fixed. New Rules for Publish are tested successfully in Pfizer.
