### ISSUE TITLE
Impact Assessment and View Version Impact : Child SMQs are not expanding in Target (right) Panel and in Target Hierarchy Search window.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#313]
1) Impact Assessment and View Version Impact : Child SMQs are not expanding in Target (right) Panel and in Target Hierarchy Search window.

![image](https://cloud.githubusercontent.com/assets/25993316/25738560/750fc014-319b-11e7-94b3-9c1bbd08bcda.png)

Note: Level 4 = PT and Level 5 = LLT

**Comment by zmeenakshi** [comment]
To be tested along with fix for: All Modules : Relations Hierarchy Search AND REPORTS (MQ DETAILED / EXPORT) : SMQ Hierarchy (Child SMQ, PTs and LLTs) are not displayed correctly in the UI #318

**Comment by zmeenakshi** [comment]
Fixed. Test before closing ticket:
![image](https://cloud.githubusercontent.com/assets/25993316/25779733/d95d4ffa-333a-11e7-85b5-ed0ef125a6c3.png)

**Comment by NehaKhosa** [comment]
![image](https://cloud.githubusercontent.com/assets/16257105/25835769/41980622-349f-11e7-8b44-dbfae5977795.png)

issue is fixed
