### ISSUE TITLE
Update: After Performing search, navigating to Update Relations directly displays last opened record.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#315]
Update module:
Steps to reproduce
1. In Update module, search any list and click on code hyperlink to view details and relations of the list. 
2. Now again on Search form, Enter TME% in list name. Click Search.
3. Do not click on any code hyperlink.  Directly click on Update Relations tab.
4. It displays the Relations of Last opened list.

In below screenshots, I did not click on Code hyperlink of TME_5May-Copy-duplicate list, but it is still displayed in update relations tab.

![image](https://cloud.githubusercontent.com/assets/26054860/25741837/439d9dc6-31aa-11e7-8d6e-b41b799d9718.png)

![image](https://cloud.githubusercontent.com/assets/26054860/25741871/62f84e5a-31aa-11e7-8347-9002153a530c.png)

**Comment by andmiel81** [comment]
I am not sure why this is an issue.

Once the user select a list from search result, the list becomes the editing one.
Until the user select another list or move to another module, it will remain as the editing one and will be available on details, notes, relations, and confirm tabs.
From what you wrote, it seems like the selected list should be reset when the user performs search (even not selecting another list).
Consider about this and if you have already did, confirm, please.

**Comment by zmeenakshi** [comment]
System should not show previously selected list details if user perform a search on the Search and clicks on (details, relations or confirm) without selecting a list. 
I search for TME list types and select one of lists and navigated to Details.
Moved back to Search, searched PRO list types but by mistake clicked on Details without selecting a list, it shows the TME I selected before. This is not good. 
So, please fix it.

**Comment by zmeenakshi** [comment]
Fixed.
