### ISSUE TITLE
IA : Colour Code for Retired and Impact Type ICC and IPC.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#317]
This is new for Retired CMQs and new IMPACT_TYPES
1) If CURRENT.CMQ_STATUS='I' then display the list name in Brown in the left panel.
2) If TARGET.IMPACT_TYPE is 'ICC' or 'IPC' then colour list name in 'navy or royal blue'  in the right panel.
3) Add these colour code to colour legend in the UI
Retire or Inactive List **(Current List)** : Brown
Indirect Impacts **(Future List)** : Royal Blue

![image](https://cloud.githubusercontent.com/assets/25993316/25760712/aefd0890-31f5-11e7-8ea8-df1975cee28f.png)

**Comment by zmeenakshi** [comment]
I don't think it done yet as I don't see retired list in brow.
The Legend text is not correct, should be updated as per the ticket provide above.

![image](https://cloud.githubusercontent.com/assets/25993316/25773441/f70e32da-329a-11e7-95f8-60d31a851273.png)

**Comment by zmeenakshi** [comment]
=> Correct the Legend:
Retire or Inactive List (Current List) : Brown
Indirect Impacts (Future List) : Dark Grey 
=> The colour of bullet from pink to match the colour for Retired, Indirect, Non-Current LLT.

** => Change the colour code for ICC and IPC to dark grey** Pasted colour sample below. Should NOT blank or light grey

![image](https://cloud.githubusercontent.com/assets/25993316/25778957/2c06aa1e-332a-11e7-8d6f-6f685a1e9fcd.png)

**Comment by NehaKhosa** [comment]
impact_type for TEST_IA_TME1 is ICC, the list is still displayed in blue instead of bold and dark grey colour.

![image](https://cloud.githubusercontent.com/assets/16257105/25837912/d60570a2-34ad-11e7-8814-79e2d043d2ff.png)

![image](https://cloud.githubusercontent.com/assets/16257105/25837936/f230c2fe-34ad-11e7-874b-2566712132d8.png)

**Comment by NehaKhosa** [comment]
Same issue with list where impact_type is IPC.
![image](https://cloud.githubusercontent.com/assets/16257105/25837957/1b232f4e-34ae-11e7-82c6-f63477c31e74.png)

![image](https://cloud.githubusercontent.com/assets/16257105/25837963/2d866fca-34ae-11e7-9219-3727974c54cb.png)

**Comment by NehaKhosa** [comment]
impact_type for TEST_IA_TME1 is ICC, the list is displayed in light grey instead of dark grey.

![image](https://cloud.githubusercontent.com/assets/16257105/25861642/fd51969a-3502-11e7-86ba-5a0e0bba4fc2.png)

**Comment by andmiel81** [comment]
"Impact_type for TEST_IA1_PRO_1 is IPC, the list is still displayed in blue instead of bold and dark grey."
I think there was some confusion here. from above DB screenshot, TEST_IA1_PRO_1 is "IMPACTED" and TEST_IA2_PRO1,and TEST_IA2_PRO2 are "IPC"

**Comment by NehaKhosa** [comment]
An oversight, apologies. 
TEST_IA2_PRO2 is "IPC" and colour coding seems to have been fixed.

![image](https://cloud.githubusercontent.com/assets/16257105/25882608/37f02ca8-3562-11e7-8399-5658067db23b.png)

TEST_IA_TME1 is ICC, the list is displayed in correct colour. 

![image](https://cloud.githubusercontent.com/assets/16257105/25882631/7854a2e2-3562-11e7-9d98-f098b7f34e64.png)

**Comment by NehaKhosa** [comment]
ISSUE RESOLVED

**Comment by NehaKhosa** [comment]
--TEST_IA_TME1 list's colour in the left pane is not correct. It should NOT be blue.
--For IPC and ICC there should be NO colour code added for the left pane.
-- Both should have default font and colour in the left pane.

![image](https://cloud.githubusercontent.com/assets/16257105/25893670/4df9023e-3596-11e7-956c-74c2c916eb67.png)

**Comment by CQTdev** [comment]
Color coding is fixed in Pfizer.
