### ISSUE TITLE
All Modules : Relations Hierarchy Search AND REPORTS (MQ DETAILED / EXPORT) : SMQ Hierarchy (Child SMQ, PTs and LLTs) are not displayed correctly in the UI & Reports

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#318]
***LIST CREATED TO TEST THE ISSUE : TME_SMQ_HIERARCHY_ISSUE***

Modules: Create, Copy, Update, Browse & Search, IA, View Version
Forms: Relations and Hierarchy Search (Current and Target)

SMQ_RELATIONS LEVELS:
SMQ_LEVEL=0 is Child SMQ (Parent SMQ details are stored in SMQ_BASE (SMQ levels are 1,2,3,4,5)
SMQ_LEVEL=4 is PT
SMQ_LEVEL=5 is LLT

 SMQ Hierarchy (Child SMQ, PTs and LLTs) are not displayed correctly in the UI.

The correct hierarchy structure is:
SMQ1-PTs
SMQ1-> SMQ2->PTs  another level 2 branch SMQ2-> PTs
SMQ1->SMQ2->PTs another level 2 branch which has a child3 SMQ2->SMQ3-> PTs another level 2 and 3 which has child 4 SMQ2->SMQ3->SMQ4->PTs 

------------------------------------------------------------
Screenshot form MedDRA Browser:
![image](https://cloud.githubusercontent.com/assets/25993316/25770955/e27e93e4-3260-11e7-9aea-4086a6ff80bb.png)

**Comment by zmeenakshi** [comment]
1)
![image](https://cloud.githubusercontent.com/assets/25993316/25771046/dfd67c26-3263-11e7-8efe-c3891956ede2.png)

2)
![image](https://cloud.githubusercontent.com/assets/25993316/25771049/1193ed5c-3264-11e7-80db-c6083385e81c.png)

3)
![image](https://cloud.githubusercontent.com/assets/25993316/25771055/30e3a346-3264-11e7-9735-d93457fae61a.png)

4)
![image](https://cloud.githubusercontent.com/assets/25993316/25771061/4a40e984-3264-11e7-9652-c64b43cbe08c.png)

**Comment by zmeenakshi** [comment]
SMQ Hierarchy issue in UI is RESOlVED..

**Comment by CQTdev** [comment]
Leyla, could you please add Designee 2 and Designee 3 rows also in MQ detailed report.

**Comment by CQTdev** [comment]
Issue fixed in Pfizer.
