### ISSUE TITLE
Update: Relations : When viewing parent list, the delete button is displayed for SMQ level assigned to the child list.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#319]
Module: Update
Form: Relations

When viewing parent list, the delete button is displayed for SMQ level assigned to the child list.

![image](https://cloud.githubusercontent.com/assets/25993316/25771813/b8b4274a-3279-11e7-959e-cf96fd5ee0f4.png)

**Comment by CQTdev** [comment]
Tested. Issue is Fixed.

![image](https://cloud.githubusercontent.com/assets/26054860/25838208/a14fda08-34af-11e7-942b-79edce1952cb.png)
