### ISSUE TITLE
Default Field Conditions Not Working Correctly on Details Page

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#32]
Module: Create/Copy/Update
Page: Details
Default field condition based on extension field are not working correctly. 
(Codelist table name is REF_CONFIG_CODELIST  and column name CODELIST_INTERNAL_VALUE)

**Comment by lsalim** [comment]
TME, TR1, DME, CPT are all level 1 lists. PRO is the only level 2. The defaults for level are still not showing correct values for the selected extension
