### ISSUE TITLE
IA and View Version Impact : No colour is appearing for Child SMQ in right and left panel.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#321]
No colour code is appearing for impacted child SMQ in left and right panel where (CURRENT / TARGET.SMQ_LEVEL=2, 3 ,4, 5 or Child SMQ (SMQ_LEVEL=0) in RELATIONS) and CURRENT / TARGET.IMPACT_TYPE=IMPACTED)
Depression (excl suicide and self-injury) (SMQ)

![image](https://cloud.githubusercontent.com/assets/25993316/25779550/fcd5072c-3338-11e7-9e8e-4b025312f7db.png)

**Comment by andmiel81** [comment]
Details please, I have looked back every documents & chat records about coloring, but not found anything related with this.

**Comment by zmeenakshi** [comment]
The IMPACTED child SMQ should be displayed in the blue colour in both right and left pane.

This is same as impact_type colouring for IMPACTED level SMQ1 SMQ.

**Comment by CQTdev** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/26054860/25845637/4ccc3b08-34cc-11e7-950c-df604306b38d.png)

**Comment by CQTdev** [comment]
Tested in Pfizer. color coding is fixed.
