### ISSUE TITLE
REQUESTOR role: User with requestor role is not able to edit list details on copy module.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#326]
REQUESTOR role: User with requestor role is not able to edit list details on copy module.

![image](https://cloud.githubusercontent.com/assets/26054860/25840002/a1f88fd8-34b7-11e7-9992-4dfeb9c35203.png)

**Comment by CQTdev** [comment]
Issue is fixed on client environment,

**Comment by ashleenkaur** [comment]
Issue fixed in DBMS and Pfizer
