### ISSUE TITLE
User with two roles(ADMIN and MQM) cannot Update/Copy lists

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#327]
![image](https://cloud.githubusercontent.com/assets/12534580/25846094/7b8c1ccc-347e-11e7-80c5-00f054967cd8.png)
![image](https://cloud.githubusercontent.com/assets/12534580/25846112/91417774-347e-11e7-84e3-cd4a699e8238.png)

A user in customer DB is assigned multiple roles(OPENCQT_ADMIN and OPENCQT_MQM). As you can see they have access to all the tabs. However even though they appear to have the ability to go into the Update and Copy tabs(as MQM role allows), the fields are read-only.

FIX: If a user has multiple roles, they must be have access per the higher access role. For example, if a user is ADMIN and MQM, then they can Update and Copy as an MQM would, even though ADMIN is not allowed to do so on it's own.

**Comment by CQTdev** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/26054860/26234201/863bee40-3c80-11e7-8b44-cf9dfc2781ab.png)


![image](https://cloud.githubusercontent.com/assets/26054860/26234208/8bebabb4-3c80-11e7-9303-28a568cdf046.png)
