### ISSUE TITLE
In IA Impact Search - State displayed is PUBLISHED instead of PUBLISHED IA

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#328]
In IA Impact Search - State displayed is PUBLISHED instead of PUBLISHED IA.

![image](https://cloud.githubusercontent.com/assets/16257105/25894600/15506e96-359a-11e7-8513-ff66904c8ed3.png)

**Comment by CQTdev** [comment]
Please add PUBLISHED also in Non-Impacted tab. The drop-down of non-impacted tab should display both, PUBLISHED IA and PUBLISHED.

**Comment by andmiel81** [comment]
This has been fixed. Test and confirm, please.

**Comment by zmeenakshi** [comment]
Fixed.
