### ISSUE TITLE
Non- Current LLTs not showing in the Target HS drop down list.

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#329]
Non- Current LLTs not showing in the Target HS drop down list.

![image](https://cloud.githubusercontent.com/assets/16257105/25895100/1f43dc38-359c-11e7-87f9-5d099a392823.png)

**Comment by CQTdev** [comment]
LLTs are now showing in Target HS. 
As per Sunil G Singh: It should be in all places where there is a HS, since user needs to see when they are using a non-current LLT.

**Comment by NehaKhosa** [comment]
LLTs displayed in Target HS. FIXED.
