### ISSUE TITLE
Credentials of user who created the old list populated in the 'Created by' field

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#331]
Before saving a copied list, the 'Created by' field is already populated with the credentials of the user who created the old list. The Created By field should be blank until the list is saved.

![image](https://cloud.githubusercontent.com/assets/16257105/25902496/50050674-35b7-11e7-97d9-606318681a48.png)

**Comment by CQTdev** [comment]
Issue is fixed in DBMS and Pfizer.
![image](https://cloud.githubusercontent.com/assets/26054860/25989082/609da3da-3718-11e7-8257-929cfc7391b3.png)
