### ISSUE TITLE
If Informative Notes are updated in IA, the parent and child impact type both should be updated.

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#334]
If Informative Notes are updated in IA, the parent and child impact type for both should be updated.

**Comment by NehaKhosa** [comment]
Condition and Type of Impact - 

If info notes for parent is updated, impact type for parent will be impacted and impact type for child will be ICC.
If info notes for child is updated then the impact type for child will be impacted and impact type for parent and siblings will be IPC.

**Comment by singhsg** [comment]
NOTE: once IMPACT_TYPE=IMPACTED for either Parent or Child, 2 iterations of Batch Impact job will set ICC/IPC status correctly for Parent/Child/Siblings.
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by CQTdev** [comment]
Issue has different behavior on both environments:

In DBMS:
1. Updating Informative notes in Non-Impacted Parent list changed the status to IMPACTED and it appeared in blue, however it didn't create a In-direct Impact on child list.
2. After running batch job, Impacted Status of Parent list changed to Non-Impacted and  Indirect impacted created for Child List.
And in Pfizer, The Direct impact never showed up, before or after impact job. Only Indirect impact is visible

**Comment by zmeenakshi** [comment]
Fixed in the UI.
Need to fix the batch job when informative notes (description) is updated for a list.

**Comment by NehaKhosa** [comment]
This is fixed.
