### ISSUE TITLE
Publish future version - unhide demote to draft subtab in UI and revise demote rules

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#336]
Left pane should show List where TARGET.CMQ_STATE='PUBLISHED IA' and TARGET.CMQ_STATUS='P'

Demote button - TARGET.CMQ_STATE='PENDING IA' and TARGET.CMQ_STATUS='P'

If level 1 list does not have any associated child, then Demote button will execute rule 1. Also, display the pre-confirmation message/panel.
Rule 1: Change the TARGET.CMQ_STATE='PENDING IA' and TARGET.CMQ_STATUS=’P’. Display the message, "The List is Demoted successfully."
If level 2 or level 1 have an associated parent/child list and both are not selected, then Demote button will execute rule 2.
Rule 2: Display the warning message, "The List being Demoted has an associated list that must be demoted." and do nothing.
If level 2 or level 1 have any associated child and both selected, then Demote button will execute rule 3. Also, display the pre-confirmation message/panel.
Rule 3: Change the state of both lists to TARGET.CMQ_STATE='PENDING IA' and TARGET.CMQ_STATUS=’P’. Display the message "The List(s) are Demoted successfully."

**Comment by CQTdev** [comment]
Tested in Pfizer. Issue is fixed.
