### ISSUE TITLE
UPDATE/COPY/BROWSE & SEARCH: Search results doesn't pull lists with PENDING IA, PUBLISHED IA, REVIEWED IA and APPROVED IA.

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#339]
UPDATE/COPY/BROWSE & SEARCH: Search results doesn't pull lists with PENDING IA, PUBLISHED IA, REVIEWED IA and APPROVED IA.

![image](https://cloud.githubusercontent.com/assets/26054860/25994056/ecc1a2a6-3729-11e7-9eb3-eabd79713d4e.png)

**Comment by andmiel81** [comment]
removed "* IA" statuses from the search filter

**Comment by CQTdev** [comment]
Issue fixed in DBMS and Client environment.

![image](https://cloud.githubusercontent.com/assets/26054860/26002321/e87709b6-374c-11e7-84bb-9df80d8c4586.png)
