### ISSUE TITLE
Add word 'Current' to both Retire and Reactivate in the Retire Module

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#340]
In UI please add the word 'current' to both Retire and Reactivate, It should appear as Retire Current and Reactivate Current.

![image](https://cloud.githubusercontent.com/assets/16257105/25995306/506be4ba-372f-11e7-82cc-3dd1cc091150.png)

**Comment by CQTdev** [comment]
Issue fixed in Client and DBMS env.

![image](https://cloud.githubusercontent.com/assets/26054860/26002273/c34ce39a-374c-11e7-8cd4-57fcb914eda2.png)
