### ISSUE TITLE
Retiring a Published IA lists should be allowed ONLY using the Demote button

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#341]
- Application is allowing user to Retire a PUBLISHED IA list which should NOT be the case.
- Retiring a Published IA lists should be allowed only using the Demote button and NOT using the Retire option.

Only Demote option should be available for Published IA/Published with cmq_state=A Target CMQs

**Comment by zmeenakshi** [comment]
Fixed as confirmed by Neha
