### ISSUE TITLE
Creating a Copy of a list when a Copy already exists, need to pick a valid name

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#342]
Module: Copy

1) User selects A002, makes a Copy, saves it. A002 - Copy now exists
2) User selects A002 again, tries to make a Copy
3) BUG: The name of the Copy is A002 - Copy (which a list of the same name already exists)
4) User tries to save and gets an error

We need to add code to detect if a list of that Copy name already exists, and if it does, append a (2) or (3) or something along those lines, to make the name unique. Same as if you create multiple copies of a file in Windows, it will always make the name unique.

**Comment by CQTdev** [comment]
Fixed. 

![image](https://cloud.githubusercontent.com/assets/26054860/26234161/3c8c9cd6-3c80-11e7-95c1-0fcb9cd05aee.png)
