### ISSUE TITLE
For Pre-loaded lists, Designee does NOT show in the UI @ Pfizer

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#344]
For pre-loaded lists, Designee does NOT show in the UI.  
See CMQ_CODE 90000309, the Designee is lamb_ja.
It should show the LDAP name similar to the created CMQs in the UI.

![image](https://cloud.githubusercontent.com/assets/16257105/26054223/6ba1e908-3989-11e7-868b-64c770f5ca64.png)

**Comment by andmiel81** [comment]
It seems like there is not user named "lamb_ja" on LDAP user list.
The designee list is coming from LDAP User list, therefore if there is no user with that specific username, it will result in empty field.

Check this with the developer who worked on LDAP issues.

**Comment by NehaKhosa** [comment]
This issue is fixed
