### ISSUE TITLE
Same Designee should NOT be selected in Designee, Designee 2 and Designee 3

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#345]
In the UI, while creating or updating a list, selection of the same Designee should not be allowed for Designee 2 and Designee 3.

Designee 2 should not equal to Designee 1.
Designee 3 should not equal Designee 2 and should not equal Designee 1.

![image](https://cloud.githubusercontent.com/assets/16257105/26064276/1661b548-39ae-11e7-8180-0c77e412eb50.png)

**Comment by NehaKhosa** [comment]
Designee 3 should not equal Designee 2 and should not equal Designee 1, the condition is MET and working at Pfizer HOWEVER if Designee 2 and Designee 3 are left blank ( as its not a mandatory field) we get a pop up - Designee 2 and Designee 3 can't be the same person.

![image](https://cloud.githubusercontent.com/assets/16257105/26101484/ebc7a4cc-3a4e-11e7-9207-41365a53ce84.png)

**Comment by andmiel81** [comment]
This has been fixed. Test and confirm, please.

**Comment by zmeenakshi** [comment]
Fixed as confirmed by Neha.
