### ISSUE TITLE
'Choose Product is required' message is displayed instead of 'Product is required.' 

### ISSUE THREAD

**Issue by CQTdev** [DBMS-Consulting/CQT2#346]
'Choose Product is required' message is displayed instead of 'Product is required.' 

![image](https://cloud.githubusercontent.com/assets/26054860/26098486/7a16b8da-3a45-11e7-8e63-caf607d3cf84.png)

**Comment by andmiel81** [comment]
This has been fixed. Test and confirm, please.

**Comment by CQTdev** [comment]
Fixed.
