### ISSUE TITLE
BUG: Can add relations to APPROVED IA

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#348]
We should *not* be able to add relations to any APPROVED list.

Select an APPROVED IA list
![image](https://cloud.githubusercontent.com/assets/12534580/26135131/815a31d0-3a81-11e7-9e6e-59e61d9cd252.png)
Add a Relation
![image](https://cloud.githubusercontent.com/assets/12534580/26135154/af7a88f8-3a81-11e7-9c52-1a836618d67b.png)
![image](https://cloud.githubusercontent.com/assets/12534580/26135167/c5d7f388-3a81-11e7-9ab6-b8e2b5e1f088.png)
Click Next
![image](https://cloud.githubusercontent.com/assets/12534580/26135177/dd6e0b04-3a81-11e7-9913-44df5fc72ea2.png)
Click Yes
![image](https://cloud.githubusercontent.com/assets/12534580/26135185/e7d4e824-3a81-11e7-92ae-b1a460247218.png)

**Comment by zmeenakshi** [comment]
Fixed. Disabled add button in Hierarchy Search and New PT windows.
