### ISSUE TITLE
POST GO-LIVE: Generate persistent entities for all new tables/views and columns from DEVCQT1 DB.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#356]
Please provide ETA here:

View Name : (Database - DEVCQT1)
CMQ_BASE_CURRENT_AUDIT
CMQ_BASE_TARGET_AUDIT
CMQ_RELATIONS_CURRENT_AUDIT
CMQ_RELATIONS_TARGET_AUDIT
CMQ_PRODUCT_BASE_CURRENT_AUDIT
CMQ_PRODUCT_BASE_TARGET_AUDIT
SMQ_CHILD_PARENT_CURRENT
SMQ_CHILD_PARENT_TARGET
CMQ_CHILD_PARENT_CURRENT
CMQ_CHILD_PARENT_TARGET

Let me know if you have any questions.

**Comment by vireshwali** [comment]
need 2 days or so to do this and test correctly...
and definitely cant do this while others are committing code rapidly....my commit will blow up everything because entities changed

**Comment by zmeenakshi** [comment]
Yesterday (24th May) Alexander created a separate development branch 'post-go-live' for post go-live tickets/updates. You should be able to proceed and as informed before the database  name is DEVCQT1.

**Comment by zmeenakshi** [comment]
Any update? This is PREVENTING other developers to continue the development for post go-live updates.

**Comment by vireshwali** [comment]
apologies for the delay....I need a day more for this please....had to change my laptop...

**Comment by zmeenakshi** [comment]
Ok. Please let me know when this is done so that I can start assigning tickets to others.

**Comment by zmeenakshi** [comment]
The precision issue for column CMQ_PARENT_CODE cann;t be resolved in SMQ_CHILD_PARENT_CURRENT and RELATIONS as data has been loaded and system is not allowing to alter the column.
Need to clear the table, and reload it again after altering column length.
