### ISSUE TITLE
Query:  Codelist value deleted from DB is displayed in UI.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#357]
1) The codelist values is not retrieved when querying the table:
![image](https://cloud.githubusercontent.com/assets/25993316/26320055/0f4c9fac-3f3f-11e7-97b1-5864666a00bc.png)

2) Appearing in UI
![image](https://cloud.githubusercontent.com/assets/25993316/26319997/e3984b0e-3f3e-11e7-80ab-c2baba813ee8.png)

3) However, when user tries to edit, the message "The codelist does not exist is displayed"
![image](https://cloud.githubusercontent.com/assets/25993316/26320087/34c73238-3f3f-11e7-98e3-8df19185c56a.png)

Query:
Do user have to clear the cache as the delete value is not immediately removed from UI or how much time does it take to reflect such change in UI.

**Comment by lsalim** [comment]
The only way for now to clear the cache is to restart the application.

An idea is develop a page clearCache.xhtml with a simple button that will call a ManagedBean method to clear the cache whenever we do an operation directly from DB.
