### ISSUE TITLE
Need Unique Combination of Codelist Type and Internal Codelist Value: Before Go-Live

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#359]
Action for DBMS; For new inserts or updates to existing Codelist values, combination of codelist type and internal codelist value *MUST* be unique and validated by the UI upon **save** or **update**

1)  For a codelist type the user should be able to same code more than once but only one of those occurrence should be active.
2) If user tries to set active flag from N to Y for an existing codelist value which can lead to duplication then system should show an error message "The active codelist value exists for the same code"

**Comment by zmeenakshi** [comment]
Fixed in 1.0.12.
