### ISSUE TITLE
Post Product Name deletion, Product code is not displayed in Update Details tab.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#366]
After inactivating Product  from the Administration module, the product code should be displayed instead of product name in the list details. But in Update Copy Details tab 'Choose Product' is displayed instead of product code.

![image](https://cloud.githubusercontent.com/assets/29117627/26671636/ddb3d824-46d3-11e7-818a-4f8dc131127a.png)

![image](https://cloud.githubusercontent.com/assets/25993316/26713524/c61e867a-478a-11e7-8eda-70f7e924595e.png)

**Comment by ashleenkaur** [comment]
Issue is not fixed. After Inactivating the Product from Administration module,, the product code is displayed only for APPROVED and PUBLISHED lists in the Update Details Tab.

For DRAFT and REVIEWED state lists, Product or Product code is not displayed in the Picklist.

**Comment by ashleenkaur** [comment]
Product code is not displayed in Products field while Product Name is INACTIVE.

![image](https://user-images.githubusercontent.com/29117627/27116327-3bd90dec-50ee-11e7-89e5-e0465ee686e8.png)

![image](https://user-images.githubusercontent.com/29117627/27116334-44d8e1b0-50ee-11e7-9d7d-1e1bd5722b6b.png)

![image](https://user-images.githubusercontent.com/29117627/27116426-bfd9096c-50ee-11e7-92bd-98bbc8d2e819.png)

**Comment by ashleenkaur** [comment]
Only ACTIVE Product name should be displayed in the Picklist for New lists.

 Product code  should be displayed only For those lists where that Product name was selected before making the Product Inactive, no matter the state is Draft, reviewed , approved or published. 

![image](https://user-images.githubusercontent.com/29117627/27227921-29b382ec-52c3-11e7-8512-2840684a93df.png)

**Comment by lsalim** [comment]
FIXED. This error was due to the cache keeping the datas even when changing modules.

**Comment by ashleenkaur** [comment]
Fixed in DBMS.

**Comment by ashleenkaur** [comment]
Fixed in Pfizer environment.
