### ISSUE TITLE
Re-order the list of levels so that PRO is not on top (setting by codelist) : Before Go-Live

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#367]
Create a codelist: 
1) SOC
2) HLGT
3) HLT
4) PT
5) LLT
6) SMQ1
7) SMQ2
8) SMQ3
9) SMQ4
10) SMQ5
11) PRO

The level drop-down in Hierarchy Search (Relations and IA) should display in the codelist order.

**Comment by ashleenkaur** [comment]
Fixed in DBMS:

![image](https://user-images.githubusercontent.com/29117627/27226009-7881ccfc-52ba-11e7-8617-4c07cf9b0e23.png)

**Comment by ashleenkaur** [comment]
Can't see Protocol in the list today.

![image](https://user-images.githubusercontent.com/29117627/27280576-03566ff2-5506-11e7-9c47-30b91eba78c0.png)

**Comment by zmeenakshi** [comment]
Fixed. Added codelist (DICTIONARY_CMQ_LEVELS)
