### ISSUE TITLE
Update module: Clicking on Cancel button does not erase fields.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#368]
In Update module
1. Search list
2. Click on the code hyperlink of the list
3. In update details tab, click cancel. Click Yes on the warning message 'Are you sure you want to erase these fields'.
4. Fields are not erased , but 'Form canceled' message is displayed.

![image](https://user-images.githubusercontent.com/29117627/26960609-321941e2-4cf6-11e7-844b-3fdc61622ef3.png)

**Comment by zmeenakshi** [comment]
What do you mean by fields are not erased?

**Comment by ashleenkaur** [comment]
In Copy module, when we click on Cancel, the form appears like below screenshot, but in update module nothing changes and just the 'Form Canceled' message is displayed.

![image](https://user-images.githubusercontent.com/29117627/26961745-c13265cc-4cfe-11e7-91df-c11673770671.png)

**Comment by ashleenkaur** [comment]
This is the expected behavior, hence closing the defect.
