### ISSUE TITLE
Before Go-Live: LLT (Drowsiness LLT code 10013649 ) is NOT appearing for CMQ 90001495 (B743_T1) which is a pre-loaded CMQ

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#371]
CMQ 90000419 which is a pre-loaded CMQ, there are 4 LLTs associated with this CMQ, which are Drowsiness, Sleepiness, Tiredness, Anemia.  But the direct relationship for the Drowsiness LLT code 10013649 does *NOT* appear in Browse and Search, but the *OTHER* three LLTs *DO* appear.  Moreover, the 4 LLTs are *CORRECTLY* show in the Export report!  Why is Drowsiness direct related LLT missing (presumably this entry exists in CMQ_RELATIONS_CURRENT)?

**Comment by ashleenkaur** [comment]
Direct LLTs Relations Drowsiness, Sleepiness, Tiredness, Anemia are not displayed in the Relation tab of List Name B7431001_T1 in the Pfizer CQT2 environment. Only two direct LLT relations are displayed which are Asthenia and Unsteadiness.

Below screenshot is from ORT501.

![image](https://user-images.githubusercontent.com/29117627/27586426-ea389de8-5b5d-11e7-8782-eaee7141e74e.png)

**Comment by zmeenakshi** [comment]
List name :  B743_T1
Code: 90001495

LLT "Drowsiness" is not appearing in UI. LLT Code is 10013649

![image](https://user-images.githubusercontent.com/25993316/27649592-d5b9cd36-5c4f-11e7-9798-3bd61e612ebc.png)

**Comment by zmeenakshi** [comment]
LLT Drowsiness is appearing in the UI.

![image](https://user-images.githubusercontent.com/25993316/27794683-c3b6ebbc-6020-11e7-87a3-8597942bf9df.png)

![image](https://user-images.githubusercontent.com/25993316/27794708-e1feb014-6020-11e7-95cb-352017daa34d.png)
