### ISSUE TITLE
Before Go-Live: If user has both MQM and Requestor then MQM permission should take precedence over Requestor

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#375]
If user has MQM and Requestor then MQM permission should take precedence over Requestor. So, user should be able to Review and Approve the list.

If they have only Requestor OR Requestor and Admin they should not be able to Approve and Review the list.

**Comment by ashleenkaur** [comment]
User has REQUESTOR and MQM roles but still cannot Review or Approve the list.

![image](https://user-images.githubusercontent.com/29117627/27082687-5c8b4e1e-5063-11e7-8d5e-4aabaddff095.png)

**Comment by ashleenkaur** [comment]
User is able to Review and Approve the list when REQUESTOR and MQM roles are assigned. However, Reason for Request and Due Date fields in Workflow section are disabled. (Screenshot 1)

And after Reviewing the CMQ, the Reviewed button is still enabled while Approve button is disabled. (Screenshot 2)

![image](https://user-images.githubusercontent.com/29117627/27115664-dfdbd5b4-50e9-11e7-9940-b1418797d5f6.png)

![image](https://user-images.githubusercontent.com/29117627/27115788-a54ed4fe-50ea-11e7-8d05-bea8fa6a822e.png)

**Comment by ashleenkaur** [comment]
If I login as MQM, then also Reviewed and Approve buttons are enabled while the status of List is already Reviewed.

![image](https://user-images.githubusercontent.com/29117627/27116150-24e64132-50ed-11e7-9efc-b78dc461f85b.png)

**Comment by ashleenkaur** [comment]
Reviewed button and Review reason, Date fields should be disabled when list is already approved.

![image](https://user-images.githubusercontent.com/29117627/27214367-b0576582-5289-11e7-91b3-94e34b7b2f0a.png)

**Comment by lsalim** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/5912923/27249067-53e759ce-52fc-11e7-9223-b9245ec1bce4.png)

**Comment by ashleenkaur** [comment]
If REQUESTOR and MQM roles are assigned to a user, Reviewed button is enabled while list is already approved. 

![image](https://user-images.githubusercontent.com/29117627/27270527-714b01be-54dc-11e7-8447-41736adbe2e7.png)

**Comment by ashleenkaur** [comment]
MQM should be able to Approve list when user has both, REQUESTOR and MQM roles. Please see the screenshot below. Approve button is disabled when list status is Reviewed.

![image](https://user-images.githubusercontent.com/29117627/27372980-202ecabe-5684-11e7-8c9c-51142954c7c6.png)

**Comment by ashleenkaur** [comment]
Fixed in Pfizer.
