### ISSUE TITLE
Pick lists - type ahead for all picklists

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#377]

**Comment by ashleenkaur** [comment]
Issue: Product Type-ahead search should be made consistent with other type-ahead search.

Product Type-ahead retrieves the terms STARTING FROM a specific searched character, whereas, Other Type-ahead search the terms CONTAINING that character, and search becomes more specific as user types more characters.

![image](https://user-images.githubusercontent.com/29117627/27327631-c89fe466-55cc-11e7-980b-8a4fcc3e8eb4.png)


![image](https://user-images.githubusercontent.com/29117627/27327710-10b4bea2-55cd-11e7-8faa-26dbac9f45ff.png)

**Comment by andmiel81** [comment]
fixed in commit fee40c4038e10f3b33e2f9a0e3aacd27a5d85b45

**Comment by andmiel81** [comment]
Check this and let me know the status, please.

**Comment by ashleenkaur** [comment]
Fixed in DBMS and Pfizer.
