### ISSUE TITLE
Before Go-Live: Creator of the list cannot update the list when REQUESTOR and ADMIN roles are assigned.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#378]
Creator of the list cannot update the list when only REQUESTOR or REQUESTOR and ADMIN roles are assigned.

**Comment by zmeenakshi** [comment]
User who have ADMIN and REQUESTOR role are not able to update the CMQ, that they are assigned as Designee or have been created by them

**Comment by ashleenkaur** [comment]
Fixed in DBMS.

![image](https://user-images.githubusercontent.com/29117627/27323327-d4c44ed4-55be-11e7-9507-c51a11adce4f.png)

**Comment by ashleenkaur** [comment]
Fixed in Pfizer.
