### ISSUE TITLE
Select All checkbox in Designee dropdown list to be removed as we have a condition of selecting only 3 designees.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#380]
Select All checkbox in Designee dropdown list to be removed as we have a condition of selecting only 3 designees so there is no purpose of keeping it.

![image](https://user-images.githubusercontent.com/29117627/27039250-07cec3c8-4fab-11e7-95c6-b4fead674e7a.png)

**Comment by zmeenakshi** [comment]
The user should be able to select All and select more than 3 in the search.
