### ISSUE TITLE
Remove Retire/Reactivate module for REQUESTOR role.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#381]
Remove **Retire/Reactivate** module for REQUESTOR role.

**Comment by zmeenakshi** [comment]
The user that has REQUESTOR should not have access to Retire/Reactivate  menu.

**Comment by ashleenkaur** [comment]
Issue is not fixed. REQUESTOR can still access the Retire/Reactivate module.

![image](https://user-images.githubusercontent.com/29117627/27083251-8b6a8234-5065-11e7-9912-9ac44699e0b1.png)

**Comment by ashleenkaur** [comment]
Issue fixed.

![image](https://user-images.githubusercontent.com/29117627/27116000-12a5a824-50ec-11e7-9707-2c10d8e18d6c.png)
