### ISSUE TITLE
Before Go-live: More than one Default in the codelist.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#382]
A codelist should only ONE Default list at the SAME TIME and the default codelist should be automatically moved to serial#1.

**Comment by ashleenkaur** [comment]
There should be only one default for all codelists and default value should be always be at top i.e., serial# should be 1
User is able to set two default values For Protocol and Product codelists.

![image](https://user-images.githubusercontent.com/29117627/27122757-4d79a104-5109-11e7-879e-ecdc5d7649c7.png)


![image](https://user-images.githubusercontent.com/29117627/27122783-60242752-5109-11e7-9fad-715d62f4bb68.png)

**Comment by andmiel81** [comment]
fixed

**Comment by ashleenkaur** [comment]
Fixed on DBMS.
