### ISSUE TITLE
Before Go-Live: When comparing SMQs in Impact Assessement the order of the SOURCE and TARGET PTs is UNKNOWN.  It should be either sorted by Code or by PT names or something configurable in the UI.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#385]
When comparing SMQs in Impact Assessement the order of the SOURCE and TARGET PTs is UNKNOWN.  It should be either sorted by Code or by PT names.   However, not having any sort order consistently makes it almost impossible for a user to understand and compare the impacts from Source (left) to Target (right).

**Comment by andmiel81** [comment]
Added sorting capability by term name or code for both source and target hierarchy

**Comment by ashleenkaur** [comment]
Sort is working fine for term name. For Code it looks similar when it is sorted in ascending order, however, it looks inconsistent in descending order.

Code column sorted in Ascending order.
![image](https://user-images.githubusercontent.com/29117627/27283002-f4b94ffa-550f-11e7-9aed-3bdbd9fce1d2.png)

Code Column sorted in Descending order. Not Matching.
![image](https://user-images.githubusercontent.com/29117627/27283049-26137ae4-5510-11e7-96f6-2319e8d44c61.png)

**Comment by andmiel81** [comment]
This is not the issue of sorting, but actual children hierarchy data mismatching.
Should be assigned to someone who was responsible for it.
