### ISSUE TITLE
Before Go-Live: PT Codes are inconsistent in Export Reports

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#386]
Check CMQ code 90001045, when running the Export report, the actual PT code for "Liver Disorder" shuld be 10024670, but INSTEAD the Export report shows 10059616.  This is BAD, as MedDRA PT and LLT codes are unique for life (throughout MedDRA versions).  This not the only case, also happens with "Acute hepatic failure" in the same CMQ and also CMQ "UAT Test 12Jun-XL" and "UT Test-Bowen", where PT Anaemia, Code is 10002034 in system , but the code is 10066761 in exported report
Also see: 
For PT:  Leukocytosis, Code is 10024378 in system , but the code is 10024279 in exported report. List name: 'UAT Test 12Jun-XL'. 
For PT:  Anaemia, Code is 10002034 in system , but the code is 10066761 in exported report.

**NOTE:** The MQ Detailed report IS correct, only the Export report is INCORRECT

**Comment by lsalim** [comment]
Fixed.

Please look for list 'test-a' since I cannot find the lists above:

![image](https://user-images.githubusercontent.com/5912923/27209197-f1952386-5239-11e7-9196-29f83cc31f7c.png)

**Comment by ashleenkaur** [comment]
Fixed in DBMS:

![image](https://user-images.githubusercontent.com/29117627/27221083-f79080f8-52a4-11e7-8845-0e1bbf835228.png)

![image](https://user-images.githubusercontent.com/29117627/27221090-fe18c912-52a4-11e7-97f7-bdcf7be15ccb.png)

**Comment by ashleenkaur** [comment]
Fixed in Pfizer.
