### ISSUE TITLE
Before Go-Live: Since Protocol, Product and Program areREQUIRED via database constraint, please put an ASTERISK next to this field in the UI for Update, Copy, Create

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#387]
The UI should show asterisk next to Protocol, Product, Program in Details page (All Modules) for all extensions. The system should show an error message if user leaves the Protocol, Program or Product empty.

**Comment by ashleenkaur** [comment]
Fixed in DBMS.
