### ISSUE TITLE
Before Go-Live: User should not be able to update the APPROVED and PUBLISHED lists.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#389]
User should not be able to update the Approved and Published lists. Though the Save and Cancel buttons are disabled but user can save the updates by clicking Yes on the message "Do you want to save the changes?"

![image](https://user-images.githubusercontent.com/29117627/27225419-a471806c-52b7-11e7-9957-9e471b67c9f6.png)

![image](https://user-images.githubusercontent.com/29117627/27225514-2fb81d0c-52b8-11e7-97ca-9e358f889c14.png)

**Comment by zmeenakshi** [comment]
The Save button is disabled but fields are updateable.

**Comment by ashleenkaur** [comment]
Fixed in DBMS.

![image](https://user-images.githubusercontent.com/29117627/27270856-cc7a0790-54de-11e7-8802-6c01296a00ed.png)

![image](https://user-images.githubusercontent.com/29117627/27270876-deae22a2-54de-11e7-919a-ea8f46058d03.png)

**Comment by ashleenkaur** [comment]
Fixed in Pfizer.
