### ISSUE TITLE
Customer environment: Issues related to Requestor and MQM role assignment.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#394]
1) REQUESTOR role: User is not able to edit newly created copied list on Copy-->Details tab. All fields are in non-edit mode. However, Informative notes can be edited and saved.
2) REQUESTOR role: In Copy module -> Details tab: Product field shrinked horizontally on clicking Cancel button.
3) MQM and REQUESTOR role: When user is assigned both MQM and REQUESTOR role, the REVIEW button is enabled when list is already reviewed and APPROVE button is disabled. Consequently, user is not able to approve the list. If user is assigned only MQM role, then there is no such issue.

**Comment by zmeenakshi** [comment]
Fixed committed on 21June. To be tested again in customer environment after deployment.

**Comment by ashleenkaur** [comment]
1. Resolved
2. Product doesn't get reset when form is canceled on copy module.
3. Resolved.

**Comment by ashleenkaur** [comment]
4. Issue resolved on customer environment.
