### ISSUE TITLE
Before Go-Live: Default values are not correct on Details tab for create module in 8080 ORT501 DB. 

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#395]
Issue: Default values are not correct on Details tab for create module in 8080 ORT501 DB. 

Product, Program and Protocol should show the default value as set in the Administration module, if not same for all list types.
That means which ever codelist is set to default in admin, the Create Details tab will show the same value for these fields.

The Default values should be like:
Product: All Products (for all list types TME,TIER-1,DME,CPT,Protocol)
Drug Program: All Programs (for all list types TME,TIER-1,DME,CPT,Protocol)
Protocol: All Protocols (for all list types TME,TIER-1,DME,CPT,Protocol)

**Comment by andmiel81** [comment]
I need confirmation about this feature:

- On creation module, product, Drug program, and protocol values are supposed to be changed according to the Extension selected.
 Therefore logically, Product, Drug Program, and Protocol's default values are decided by the Extension's default value accordingly.

- In this ticket, Product, Drug program and Protocol fields are supposed to have their own default values.

These two requests conflict with each other.
Let me know which one we should prioritize.

**Comment by ashleenkaur** [comment]
**From SGS**: For Andrius's question, can you clarify that there should not be any case, based on the extension, where there is a BLANK for the default value of Program, Product or Protocol.  Or in other words, in any cases where there is a BLANK being shown based on the CURRENT LOGIC of default values by EXTENSION TYPE for Program, Protocol and Product, the DEFAULT which is in the Codelist Configuration should be used instead.

**Comment by ashleenkaur** [comment]
For DME and CPT type codelists, it is still displaying Choose Products in product codelist.

![image](https://user-images.githubusercontent.com/29117627/27525606-ead65e68-5a5c-11e7-84a3-9110f526a580.png)

**Comment by andmiel81** [comment]
I have checked the issue:

To understand the problem, first refer to #230.
In description of #230, for CPT and DME, the default value of Product is "No Product".
And we coded under the assumption, that the "No ***" will be constants. (Protocol, Product, etc)
For example, "No product" is mapped to "99999".

I see that on 8080 ORT501, "No Product"'s code is set to "P300". Thus this is causing the issue.
Discuss this with the business team, and let me know the decision.

Thanks.

**Comment by ashleenkaur** [comment]
The default values (Extension, Product, Protocol and Program) for all list (TME, CPT, PRO, DME, TR1) should be what is set as default (check the default is Y) in the Administration. Remove any list based condition for default values of Product, Protocol and Program, that is no longer required.

**Comment by singhsg** [comment]
This needs to come from codelist now based on default flag
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by zmeenakshi** [comment]
![image](https://user-images.githubusercontent.com/25993316/27546344-2475c994-5ab0-11e7-8a72-37f37aa5bf4d.png)

![image](https://user-images.githubusercontent.com/25993316/27546403-4ad41186-5ab0-11e7-95de-cf62ef2f06dd.png)

![image](https://user-images.githubusercontent.com/25993316/27546425-5839832e-5ab0-11e7-803e-0b4947800c44.png)
