### ISSUE TITLE
Before Go-Live: Need to increase the session out time.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#396]
OpenCQT doesn't respond if left idle for sometime. Tested it for 10 mins duration.

**Comment by singhsg** [comment]
Hi, customer has asked any idle timeout be *configurable* and *set for 4 hours*
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by zmeenakshi** [comment]
Not a requirement.
