### ISSUE TITLE
Before Go-Live: Creator of the CMQ is not able to update the list with Requestor role.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#397]
Creator of the CMQ is not able to update the list with Requestor role.

![image](https://user-images.githubusercontent.com/29117627/27526086-0837f10c-5a61-11e7-8608-9f7de8c99968.png)

**Comment by zmeenakshi** [comment]
![image](https://user-images.githubusercontent.com/25993316/27546287-04904f50-5ab0-11e7-9807-59b2cebf96b6.png)
