### ISSUE TITLE
Before Go-Live:  Scope, Weight and Category values are not displayed in the MQ Detailed Report.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#398]
Scope, Weight and Category values are not displayed in the MQ Detailed Report. 

![image](https://user-images.githubusercontent.com/29117627/27533281-9f6ec7de-5a80-11e7-90a8-6cfad88ec637.png)

**Comment by ashleenkaur** [comment]
Please Add Scope column in Export report for all modules.
MQ detailed report is not showing scope for SMQ.

**Comment by ashleenkaur** [comment]
Fixed in DBMS

**Comment by zmeenakshi** [comment]
Fixed in all modules other than IA.
