### ISSUE TITLE
Before Go-Live: Rules for Reviewed and Approve buttons.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#399]
Issue: Review Button is enabled for INACTIVE List. 

![image](https://user-images.githubusercontent.com/29117627/27534617-447351a6-5a85-11e7-8d3a-4262815d477f.png)

User should not be able to Review or Approve an INACTIVE List.
Below are the rules for Reviewed and Approve buttons:

DRAFT: Workflow state of a new list is Draft. Only Reviewed and Delete button should be enabled when list's current state is Draft. Only lists which are in Draft state can be deleted.

DRAFT to REVIEWED: User can move list from Draft to Reviewed state by clicking Reviewed button on the confirm page. 

REVIEWED to APPROVED or DRAFT: APPROVED  and Demote to Draft buttons should be enabled when list's state is REVIEWED. A  list in Reviewed state can either be Approved or Demoted (change status back to Draft).

APPROVED to PUBLISH or Draft: A list in APPROVED state can either be promoted to Publish or demoted to Draft. When a list is in APPROVED state, only Demote-to-Draft button is enabled.

**Comment by zmeenakshi** [comment]
![image](https://user-images.githubusercontent.com/25993316/27546152-9951bd50-5aaf-11e7-822b-67f56fe18897.png)
