### ISSUE TITLE
Before Go-Live: Delete button is disabled on Confirm tab when list is in DRAFT PENDING state AFTER reactivation. 

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#401]
In Pfizer CQT2 - Delete button is disabled on Confirm tab when list is in DRAFT PENDING state **AFTER** reactivation. 

![image](https://user-images.githubusercontent.com/29117627/27586751-42c7d7d4-5b5f-11e7-8b9a-c08f73896dfb.png)

**Comment by andmiel81** [comment]
Isn't this conflicting with #247, and other ticket(not sure of the ticket number)?

#247 requires the once-approved list not being able to be deleted.
The other ticket required once-activated list not being able to be deleted.

In this ticket, Doesn't once-activated mean approved once already?

**Comment by zmeenakshi** [comment]
This is NOT an issue but expected behavior.
