### ISSUE TITLE
Update module: Save warning message displays on clicking next button on Update details tab even when list details are not updated.

### ISSUE THREAD

**Issue by ashleenkaur** [DBMS-Consulting/CQT2#407]
Update module: Save warning message displays on clicking next button on Update details tab even when list details are not updated.

**Comment by andmiel81** [comment]
updated.

**Comment by andmiel81** [comment]
@test team.
Give specific CQT List's code that shows this bug.
Thanks.

**Comment by andmiel81** [comment]
fixed

**Comment by zmeenakshi** [comment]
This was related to config data case mismatch issue. Fixed.
