### ISSUE TITLE
Search (All Modules) : The Internal code is displayed for Protocol instead of codelist value.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#408]
Copies of the Protocol CMQs default to the INCORRECT Protocol, see LIST in Pfizer (90001588 and 90001589).  The Code for PRO001 is shown and NOT the Protocol name itself. Moreover, the CODE should ONLY be displayed if the Protocol was NOT Active. In these cases, two issues exist: The code refers to the WRONG protocol based on the copy AND the Protocol Code is shown for an ACTIVE protocol and the Protocol name (Codelist Value as opposed to internal codelist value) should be shown instead.

**Comment by andmiel81** [comment]
@Test team:
I think the problem is with the upper and lower cases of the protocol value.

the internal code value of the specific protocol has been changed case-only.
And therefore, working unexpectedly.

**Comment by zmeenakshi** [comment]
The admin module should not convert codelist code and value to upper case. It should allow mix case code and value for chararcter entries.

**Comment by andmiel81** [comment]
Need clarification on this:

 - Is codelist internal value case-sensitive?

If true, the solution to this issue would be manually updating protocol_id field of CMQ lists.
If false, the code should be changed to deal with it.

**Comment by zmeenakshi** [comment]
![image](https://user-images.githubusercontent.com/25993316/28114682-77c04298-671f-11e7-901d-9511959f7e84.png)

**Comment by andmiel81** [comment]
updated

**Comment by zmeenakshi** [comment]
Andrius fix resolved the issue.
