### ISSUE TITLE
Search (All Modules)  : The search is not working when search by Protocol.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#409]
in OpenCQT Browse and Seearch, selecting a specific protocol for searching, such as A7281007 does NOT return the CMQs (lists) which contain this protocol (observed in devcqt2).

**Comment by andmiel81** [comment]
I have checked the full list of LIST manually.
It seems like there is no LIST with protocol "A7281007".
Worked fine from what I see.

**Comment by singhsg** [comment]
It is definitely *NOT* working correctly. Please create and identify some other test cases.

Thanks,
Sunil G. Singh
DBMS Consulting, Inc
singh@clinicalserver.com
+1-860-983-5848

**Comment by andmiel81** [comment]
The cause is similar to #408 's.

the problem is with the upper and lower cases of the protocol value.

the internal code value of the specific protocol has been changed case-only.
And therefore, working unexpectedly.

**Comment by singhsg** [comment]
Hi, can a code update be made to handle case sensistivity properly? Also why has the case changed?
Thanks,
Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by andmiel81** [comment]
updated

**Comment by zmeenakshi** [comment]
Fixed in 1.0.26.
