### ISSUE TITLE
Relations Read-Only Fields

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#41]
Module: Create/Update/Copy
Page: Relations

The Display following List Name, List Level, Scope, Weight, Category. Scope, Weight, Category should be read-only fields.

**Comment by andmiel81** [comment]
Clarification required:
Currently showing:
   Name [read-only], Code [read-only], Level [read-only], Scope [editable],  Category [editable], Weight [editable].

As to make Scope, Weight, Category read-only, there is nowhere to pull such data without user editing.

**Comment by zmeenakshi** [comment]
Alexander, please test and close.

**Comment by zmeenakshi** [comment]
Same as #101
