### ISSUE TITLE
Impact Assessment  (Impact Search window) State dropdown is overlapped by the window.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#411]
The impact search window is dynamically resized per search results/row, which is not is causing this overalp with rows returned is less.

![image](https://user-images.githubusercontent.com/25993316/28072043-5a08698e-666f-11e7-8a5e-7deec6ddf719.png)

**Comment by andmiel81** [comment]
updated

**Comment by zmeenakshi** [comment]
![image](https://user-images.githubusercontent.com/25993316/28367208-96886726-6cad-11e7-8006-8d1c166a06f7.png)
