### ISSUE TITLE
Priority (MEDIUM) : System Test: In the MQ Detailed Report, Child-SMQ level 4 and 5 and the PTs for Child-SMQs level 3, 4, 5 are not retrieved.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#413]
![image](https://user-images.githubusercontent.com/25993316/28367750-af4e8176-6caf-11e7-8182-2ed6d4a09bf4.png)
![image](https://user-images.githubusercontent.com/25993316/28367775-bf43843c-6caf-11e7-919e-4b7836e5df47.png)

![image](https://user-images.githubusercontent.com/25993316/28368389-cca01db4-6cb1-11e7-88f5-27e5066c51f3.png)

![image](https://user-images.githubusercontent.com/25993316/28368409-deb406c8-6cb1-11e7-8c6a-7173928a35a2.png)

**Comment by lsalim** [comment]
Root cause: the way it was coded, the MQ detailed export method was only fetching one level of SQMs relations for CHILD SMQ. The code has been updated to get child relations from CHILD SMQs also.

**Comment by singhsg** [comment]
Hi, Please kindly test on an SMQ that has 5 levels.  Use the SMQ_PARENT_CHILD_CURRENT view (similar name) to find such an SMQ quickly.

Thanks,
Sunil G. Singh
DBMS Consulting, Inc
singh@clinicalserver.com
+1-860-983-5848

**Comment by zmeenakshi** [comment]
1) Add MQ Detailed Report fix to IA and View Version Import Export. 
2) Add the Scope column
3) The MedDRA version in the report should be TARGET dictionary version NOT CURRENT. 
4) Status is showing PENDING instead of PENDING IA
5) Remove scope.
![image](https://user-images.githubusercontent.com/25993316/28776494-7d9642ea-7614-11e7-86be-bdabf393f657.png)

**Comment by zmeenakshi** [comment]
MQ Detailed Report is fixed.
[Relations_MQ_Detailed_Report_TME_MQ_DETAILED_REPORT.xlsx](https://github.com/DBMS-Consulting/CQT2/files/1187426/Relations_MQ_Detailed_Report_TME_MQ_DETAILED_REPORT.xlsx)
[Relations_MQ_Detailed_Report_TME_MQ_DETAILED_REPORTHepatic disorders (SMQ).xlsx](https://github.com/DBMS-Consulting/CQT2/files/1187429/Relations_MQ_Detailed_Report_TME_MQ_DETAILED_REPORTHepatic.disorders.SMQ.xlsx)

**Comment by zmeenakshi** [comment]
Following IA Export issues have been fixed:
[Impact_Assessment_Report_EXPORT_ISSUE_TEST_TME.xlsx](https://github.com/DBMS-Consulting/CQT2/files/1211604/Impact_Assessment_Report_EXPORT_ISSUE_TEST_TME.xlsx)

1) State
2) Dictionary Version.
3) Scope
4) Child SMQ and PTs
