### ISSUE TITLE
UAT Stage Protocol Search issue (Defect #5)

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#417]
This looks like a data load issue: Protocol is loaded using Protocol Name instead of Protocol Internal Code.
Pfizer Stage:
![image](https://user-images.githubusercontent.com/25993316/28533982-a423fd88-70bc-11e7-8d6a-077364c41fa7.png)

DBMS 8080:
![image](https://user-images.githubusercontent.com/25993316/28534245-b21bdce8-70bd-11e7-98aa-5ac6614a041a.png)

**Comment by zmeenakshi** [comment]
Administration : Protocol:
![image](https://user-images.githubusercontent.com/25993316/28535022-891ee9ea-70c0-11e7-8d00-2b82b3ccdbe8.png)

Searching for Protocol: A0221047 returns following records. No record is retunred for PRO (A0221047)
![image](https://user-images.githubusercontent.com/25993316/28535193-111b2ce6-70c1-11e7-9f8c-cdc9444aabaf.png)

**Comment by zmeenakshi** [comment]
No record is returned for PRO (A0221066)

![image](https://user-images.githubusercontent.com/25993316/28535332-96420818-70c1-11e7-9041-ebe4e2ea6dd8.png)

**Comment by singhsg** [comment]
Does this *also* occur on DBMS 8080 environment and also customer DEVCQT2 environment?

Thanks,
Sunil G. Singh
DBMS Consulting, Inc
singh@clinicalserver.com
+1-860-983-5848

**Comment by zmeenakshi** [comment]
Yes.

**Comment by zmeenakshi** [comment]
Fixed in Pfizer's CQTDEV instance.
