### ISSUE TITLE
Stage (Defect 13 and 14): System accepts more than 6 chars for extension code in Admin module, but displays error when using extension code longer than 6 chars in Create module.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#418]
CMQ_BASE_191: The length for list attributes is as mentioned below:
CMQ_TYPE_CD : VARCHAR2 (6 BYTE)
CMQ_PROGRAM_CD: VARCHAR2 (200BYTE)
CMQ_PROTOCOL_CD: VARCHAR2 (100 BYTE)
CMQ_PRODUCT_CD: VARCHAR2 (200BYTE)

REF_CONFIG_CODELIST:
CODELIST_INTERNAL_VALUE : VARCHAR2 (200 BYTE)

Should this added to user training for now and addressed post go-live?

**Comment by singhsg** [comment]
Yes, it should be documented in the release notes and the training for now.

Thanks,
Sunil G. Singh
DBMS Consulting, Inc
singh@clinicalserver.com
+1-860-983-5848

**Comment by zmeenakshi** [comment]
The column length of CMQ_TYPE_CD_OLD and CMQ_TYPE_CD_NEW in CMQ_BASE_191_AUDIT and 200 is 3 characters while CMQ_TYPE_CD column length is 6 character in CMQ_BASE_191 and 200 tables.

On Creating a List using extension code more then 3 characters, the system showing error "ORA-12899: valiue to large for column."
![image](https://user-images.githubusercontent.com/25993316/28830875-b404006a-76f5-11e7-8a2b-6bfecf0fbff6.png)

**Comment by zmeenakshi** [comment]
New ticket open and work in progress #457
