### ISSUE TITLE
Relations Page Additional Fixes and Functionality

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#42]
Page: Relations
1) Only SMQ search is working.
2) Save Relations is not working.
3) MQ Details

**Comment by vireshwali** [comment]
fixed SMQ and Meddra levels listing and moving to relations table from hierarchy table.
Save done for SMQ and Meddra levels searches.
MQ details also saved with the relations int he relations tables...

**Comment by vireshwali** [comment]
Closing the issue as fixed.
