### ISSUE TITLE
Defect: MDC View is showing TR1 instead of Tier-1 in the column LIST_TYPE.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#434]
![image](https://user-images.githubusercontent.com/25993316/29414832-9b66c142-837e-11e7-9a14-8ef324517f0e.png)

**Comment by zmeenakshi** [comment]
Issues resolved:
![image](https://user-images.githubusercontent.com/25993316/29415701-7c18cdbe-8381-11e7-81ed-b29575bb2842.png)

**Comment by zmeenakshi** [comment]
Screenshot for PRO list type showing : TIER-1 in LIST_TYPE column.
![image](https://user-images.githubusercontent.com/25993316/29417617-6ff72c32-8387-11e7-9b41-c88783208658.png)

**Comment by singhsg** [comment]
Yes, the parent list type is propagated to the child lists.

Sunil G. Singh
DBMS Consulting, Inc
+1-860-983-5848
singh@clinicalserver.com

**Comment by zmeenakshi** [comment]
PRO list type showing TIER-1 in LIST_TYPE column.. Added a screenshot to show that TIER-1 conversion for both Tier-1 and Protocol (where parent is Tier-1 list) lists
