### ISSUE TITLE
Priority Medium: Impact Assessment : Issues when exporting SMQ  including performance issue.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#439]
Step to reproduce the issue:
1) Select SMQ Depression and suicide/self-injury (SMQ)
2) Expand Suicide/self-injury (SMQ)
![image](https://user-images.githubusercontent.com/25993316/29627987-aa7ca2dc-8851-11e7-98e0-e72e81d0264b.png)

2a) Why is RELATION_IMPACT_TYPE NTR is concatenated with the term below
![image](https://user-images.githubusercontent.com/25993316/29627971-96deb904-8851-11e7-849c-273d17a34708.png)

3) Again, NTR is concatenated with TERMs. 
3b) The Scope is missing for some of the terms (it should show broad in this case)
![image](https://user-images.githubusercontent.com/25993316/29628085-0bce9bc6-8852-11e7-87cb-de03265994a8.png)

![image](https://user-images.githubusercontent.com/25993316/29628154-4ac475f8-8852-11e7-9f24-bc789ee6602b.png)

4) Remove Scope Yes/No

**Comment by zmeenakshi** [comment]
1) Select Biliary  Disorders (SMQ) from Non-Impacted SMQ
2) The report is not showing PT corresponding to the Child SMQ.
![image](https://user-images.githubusercontent.com/25993316/29628490-37654a54-8853-11e7-8740-24927acc4b1d.png)
![image](https://user-images.githubusercontent.com/25993316/29628522-5e9df3aa-8853-11e7-9e99-1c6fa77ad740.png)

3) The Child SMQ appearing again and its corresponding PTs are displayed from row 122
3a) Scope is missing; again Broad is not displayed.
![image](https://user-images.githubusercontent.com/25993316/29628584-930c8124-8853-11e7-9fb4-6e0164fe37b8.png)

**Comment by lsalim** [comment]
2a) Why is RELATION_IMPACT_TYPE NTR is concatenated with the term below " : It was an error in the code : this should have been removed

**Comment by zmeenakshi** [comment]
Add column Impact Type in the export for SMQ.

**Comment by zmeenakshi** [comment]
Fixed in version 1.0.27.
