### ISSUE TITLE
Release 2 : Priority 1: Add another option to search an SMQ not restricted to a specific level, in addition to current the level SMQ1 to SMQ5 search options.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#454]
Leyla : Add level SMQ All (Hierarchy Seach all modules): 30mins : 19-Oct-2017
Commit code after adding level option, and inform Viresh.

Viresh : Search code: 4 hours 
20-Oct-2017

------------------------------------------------------------------------------------------------
Description:
=> Need to add   another option to search an SMQ not restricted to a specific level, in   addition to current the level SMQ1 to SMQ5 search options. 
=> Add   drop-down option **SMQ ALL** option to   level drop-down to search across SMQ levels.   This is   required for the cases where users do not know the SMQ level.

**Comment by zmeenakshi** [comment]
Please remove the  SMQ filter options. Instead add "SMQ ALL' in the Level drop-down.
![image](https://user-images.githubusercontent.com/25993316/31808236-e3e03b22-b58f-11e7-821f-3873f5704fb7.png)

Since the list of value/drop-down is codelist drive, so there is no need to update code. I've added 'SMQ ALL' to the dictionary level 

![image](https://user-images.githubusercontent.com/25993316/31808466-e49c2d36-b590-11e7-976a-75cea9523c45.png)

Viresh, please update the search to code. The system should search all SMQ levels (1 to 5) when level is SMQ ALL to return the search SMQ. This is required in cases where users do not know the SMQ level.

**Comment by lsalim** [comment]
Drop-down removed!

**Comment by zmeenakshi** [comment]
Tested  in 25th Oct in 8080.
ISSUE: NOT working in IA right/target panel HS.
![image](https://user-images.githubusercontent.com/25993316/31983382-b5a68b00-b97a-11e7-8ba5-e6287aa0aea1.png)
----------------------------
Working in Create/Update/Copy HS and IA left panel HS.
![image](https://user-images.githubusercontent.com/25993316/31983400-cb7fed9a-b97a-11e7-99df-85b318ae2649.png)
-------------------------------
![image](https://user-images.githubusercontent.com/25993316/31983428-e140bb96-b97a-11e7-84f8-4a683cda4115.png)
----------------------------------
![image](https://user-images.githubusercontent.com/25993316/31983491-167c3c18-b97b-11e7-88a4-92c257072c74.png)
----------------------------------

**Comment by zmeenakshi** [comment]
Fixed in November 2017 release.
