### ISSUE TITLE
Release 2 : Priority 1 : The Show Primary Path check-box is disabled in Hierarchy Search Target pop-up window.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#463]
Issue: The Show Primary Path check-box is disabled in Hierarchy Search Target pop-up window initially as user navigates to module first time for the default level PT.
Note: After setting level to LLT and back to PT, it works correctly. 

![image](https://user-images.githubusercontent.com/25993316/31808635-b7815e42-b591-11e7-9a6e-5d6aba695fa9.png)

**Comment by lsalim** [comment]
Is this an issue? In the code I see that there is specific condition that shows when to disable the checkBox: when level != 'PT' or leb-vel != 'LLT'.

**Comment by zmeenakshi** [comment]
Yes, this is an issue because show primary path check-box is for some reason disabled when Hierarchy Search (target) window is invoked the first time.
The condition is correct but there seems to some issue that it doesn't work initially.

**Comment by zmeenakshi** [comment]
Issue is fixed. Tested on 25-Oct-2017
![image](https://user-images.githubusercontent.com/25993316/31992353-b696c27e-b997-11e7-8aa5-fc1e4394b13c.png)

**Comment by zmeenakshi** [comment]
Fixed in November 2017 release.
