### ISSUE TITLE
Release 2 : Priority 1 : IA Hierarchy Search Target : Expand icon is NOT displayed for SMQ1 search result.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#464]
The expand icon is NOT displayed for SMQ1 search result when searching SMQ first time. Users have to click on the search button twice.

![image](https://user-images.githubusercontent.com/25993316/31816618-a9cbb15e-b5ae-11e7-92e6-e30ed80da89d.png)

Note: In general there is an issue with the default behaviour of Search Direction radio button.
=> Select SMQ2 : The search direction changes to after pressing Search key, but displays upward hierarchy and same is for other levels too.
![image](https://user-images.githubusercontent.com/25993316/31816751-1f8963b4-b5af-11e7-9a01-9900aed68a6c.png)
-----------
![image](https://user-images.githubusercontent.com/25993316/31816758-254c5c5c-b5af-11e7-869b-77fa62febc20.png)
------------
![image](https://user-images.githubusercontent.com/25993316/31816885-9a482180-b5af-11e7-9a37-f77cf884aff6.png)
The inner grid (showing terms) is getting overlapped by button as it dynamically expanded to 15 rows.

**Comment by lsalim** [comment]
When I searched for SMQ1, then click for the first time on Search, It seems to be working. Looking for the other issues:
<img width="688" alt="screen shot 2017-10-22 at 11 01 27 am" src="https://user-images.githubusercontent.com/5912923/31861199-8b3f11de-b718-11e7-8067-95de7b181e69.png">

**Comment by zmeenakshi** [comment]
You need to look into IA - Hierarchy Search Target window NOT in the CURRENT.

**Comment by zmeenakshi** [comment]
Fixed on 24-Oct-2017 and tested in 8080 on 25-Oct-2017.
![image](https://user-images.githubusercontent.com/25993316/31992059-df849982-b996-11e7-9d7d-c3837a4dbca6.png)

**Comment by zmeenakshi** [comment]
Issue: Default setting for Up and Down radio button is not working in IA HS Target window.
Default Settings are:
1) PT : Up
2) LLT : Up
3) HLT : Down
4) HLGT : Down
5) SOC : Down
6) SMQ1: Down
7) SMQ2: Down
8) SMQ3: Down
9) SMQ4: Down
10) SMQ5: Up
11) SMQ All: Down

**Comment by zmeenakshi** [comment]
Fixed in November 2017 release.
