### ISSUE TITLE
Designee Type-Ahead bug, not working in Create/Update/Copy Details  page

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#474]
Module: Create/Update/Copy
Page: Details

The type-ahead in Search is working fine. Let me know if additional details/screenshots are needed.

![image](https://user-images.githubusercontent.com/12534580/33131313-23df0f1c-cf64-11e7-9718-5342a19b5432.png)
![image](https://user-images.githubusercontent.com/12534580/33131326-3112258e-cf64-11e7-863e-bbb12fffd7e1.png)

**Comment by lsalim** [comment]
Added an option on the dropdown component to add typeahed option in the code and override typeahead done from the navigator.
To test in customer environnement.
