### ISSUE TITLE
User can access details in the Impact Assessment Module when you have an SMQ selected 

### ISSUE THREAD

**Issue by dcamarda** [DBMS-Consulting/CQT2#482]
Module: Impact Assessment
Page: Notes/Details

Issue: When an SMQ is selected and changes are made to the Informative Notes tab you are able to switch to the details page despite the warning message: "Details tab is not accessible for SMQs". When you have unsaved changes and try to move to details, you can either select yes or no to the unsaved changes warning and it will allow you to move into the details page. It will not save the Informative Notes either way.

**Comment by zmeenakshi** [comment]
8080:
![image](https://user-images.githubusercontent.com/25993316/82431761-b4682d00-9aac-11ea-941f-41cc51a046b7.png)

8383:
![image](https://user-images.githubusercontent.com/25993316/82431883-e37e9e80-9aac-11ea-847c-85711e8a0c3c.png)
