### ISSUE TITLE
Delete Selected Terms in Relations Page

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#52]
Module: Create/Update/Copy
Page: Relations

Should be able to select items in the Relations table, and when Delete Selected is clicked, and the Yes button is clicked in the popup, those items are deleted from the list, along with any child-objects they had.

**Comment by vireshwali** [comment]
This is done in create module flow. Th update and copy modules have some problem in primefaces wizard which leyla has to fix for these to be tested further.

**Comment by zmeenakshi** [comment]
The Delete Selected button is not deleting data from the DB. 
Not sure who is working on this ticket as Leyla removed assignment without reassigning to anyone.

**Comment by andmiel81** [comment]
Currently logic is as follows:

When clicking on delete button from each row, after confirm dialog, it deletes the relation from both the UI and the DB.
When clicking on delete selected from the form, it will delete the relation from the UI only and not save the changes to the DB, just until the save button is clicked. ( This had logical errors and bugs, which are now fixed. )

**Comment by zmeenakshi** [comment]
REMOVED "DELETE SELECTED" button from the relations as it never worked as expected.  Row level delete will enable user to delete the relations.
