### ISSUE TITLE
IA (right/target panel): The scope drop-down should be disabled when Protocol list (level 2) is not the selected the list

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#521]
Here the selected list is TR1_LIST_06May2020 and PRO_LIST1_06May2020 is displayed when expanding the TR1 (parent) list. The scope should displayed as a readonly field.

![image](https://user-images.githubusercontent.com/25993316/82016931-a0cd5880-969f-11ea-8d5a-32c7842a4342.png)

**Comment by dcamarda** [comment]
Fix has been pushed and deployed

**Comment by zmeenakshi** [comment]
Fixed in JBoss 7.2 (Port 8383)
![image](https://user-images.githubusercontent.com/25993316/82413335-c63cd680-9a92-11ea-87f3-f7408e39ccd8.png)
