### ISSUE TITLE
PT added from SMQ can not be expanded in the Relations and IA Export. 

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#525]
1) A PT added from SMQs cannot be expanded to see the LLTs under it in the user interface.
2) The Detailed Report and IA Export reports do not show LLTs under PT, when a PT is added from SMQ.

**Comment by zmeenakshi** [comment]
1) Issue: Weight and Scope are not displayed in the Relations->Export for the PTs added from SMQ.
![image](https://user-images.githubusercontent.com/25993316/105971958-199b0600-60b1-11eb-80a0-5b3645c4befb.png)
[Report_SMQ_PT_DELETE_ISSUE.xlsx](https://github.com/DBMS-Consulting/CQT2/files/5879092/Report_SMQ_PT_DELETE_ISSUE.xlsx)

**Comment by zmeenakshi** [comment]
1) The PTs added from SMQ cannot be expanded in the IA form.
![image](https://user-images.githubusercontent.com/25993316/105973353-a72b2580-60b2-11eb-9c1e-f21221769bd1.png)

**Comment by narenderbisht** [comment]
This is fixed

**Comment by zmeenakshi** [comment]
PT added from SMQ can not be expanded after Filter out LLT check-box is unchecked.
Steps to reproduce the issue: 
1) Added a PT from SMQ. Click Save.
2) Expand the PT.
3) Check-on Filter out LLT check-box. Expand icon is no longer displayed all PTs added to the List.
4)  UnCheck Filter out LLT check-box. Expand icon is no more displayed for the PTs added from SMQ.

=> Issue is fixed in MQ  Detailed Report.

Before: Step 2
![image](https://user-images.githubusercontent.com/25993316/112128884-dd85ac80-8bec-11eb-9c41-8934f0aa82c4.png)
After: Step 4
![image](https://user-images.githubusercontent.com/25993316/112129644-a06dea00-8bed-11eb-985c-046394cbddac.png)
[Relations_MQ_Detailed_Report_PRO SMQ LLT PT 25JUNE2020.zip](https://github.com/DBMS-Consulting/CQT2/files/6188584/Relations_MQ_Detailed_Report_PRO.SMQ.LLT.PT.25JUNE2020.zip)
[Relations_MQ_Detailed_Report_PRO SMQ LLT PT 25JUNE2020 (1).zip](https://github.com/DBMS-Consulting/CQT2/files/6188585/Relations_MQ_Detailed_Report_PRO.SMQ.LLT.PT.25JUNE2020.1.zip)

**Comment by zmeenakshi** [comment]
**The PT, added from SMQ, can not be expanded for the child List in UI. Steps to reproduce:**
1) Select any TR1_NORELATIONS_TEST3 (Parent List)
2) Go to Relations
3) PT added from SMQ can not be expanded. (Under child list)
![image](https://user-images.githubusercontent.com/25993316/117540237-db0bd480-b02b-11eb-98de-f3aa361f8f60.png)

**In this case, the MQ Detailed report is also also not showing LLTs.**
