### ISSUE TITLE
Scope, Weight and Category are not displayed in the UI, and Scope and Weight are not displayed in reports.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#526]
In release 1.0.43, the scope, weight and category are NOT inherited from SMQ.
In release 1.0.43, the category is manually assigned by users during list creation or list updated to the Tier-1 lists relation.

Issue:
Before release 1.0.43, when a PT was added from an SMQ, the scope, weight and category were inherited from the SMQ.
1) Scope, Weight and Category are not displayed on the interface for the Lists created before release 1.0.43, which contain PTs added from SMQ.
2) For these case, the MQ Detailed Report shows only category. The scope and weight are not displayed in the report.

Please see SMQ_PT_DELETE_ISSUE Code 90004210.

**Comment by zmeenakshi** [comment]
Issue: Weight and Scope are not displayed in the Relations->Export for the PTs added from SMQ. List Name: SMQ_PT_DELETE_ISSUE
[Report_SMQ_PT_DELETE_ISSUE.xlsx](https://github.com/DBMS-Consulting/CQT2/files/5879257/Report_SMQ_PT_DELETE_ISSUE.xlsx)

**Comment by narenderbisht** [comment]
This is fixed

**Comment by zmeenakshi** [comment]
Issue resolved in Create and Update. Pending IA
[Relations_MQ_Detailed_Report_PRO_IACAT_TEST1_14JULY2020.zip](https://github.com/DBMS-Consulting/CQT2/files/6189170/Relations_MQ_Detailed_Report_PRO_IACAT_TEST1_14JULY2020.zip)
:
![image](https://user-images.githubusercontent.com/25993316/112132992-39eacb00-8bf1-11eb-9fd4-e95a1483c394.png)
[Relations_MQ_Detailed_Report_IA_PRO_C1_29JAN2019_LIST2.zip](https://github.com/DBMS-Consulting/CQT2/files/6188781/Relations_MQ_Detailed_Report_IA_PRO_C1_29JAN2019_LIST2.zip)

![image](https://user-images.githubusercontent.com/25993316/112139087-5b9b8080-8bf8-11eb-8ed6-def45b3aae47.png)

**Comment by zmeenakshi** [comment]
Issue is present in Impact Assessment module.
1) Category and weight are not displayed for SMQ in UI
2) Weight is not displayed in the IA Export.
![image](https://user-images.githubusercontent.com/25993316/112136571-2477a000-8bf5-11eb-81d6-f8bdb0d393e4.png)
![image](https://user-images.githubusercontent.com/25993316/112136622-348f7f80-8bf5-11eb-89c8-6742e8b8dbd2.png)
