### ISSUE TITLE
Created List's Relations Not Appearing in Update/Copy

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#56]
Module: Create/Update/Browse
Page: Add-Relations/Relations

steps to recreate:
1) Create a new list
2) Search for a hierarchy term, add to relations
3) Save everything
4) Search for your list in Update
5) Select list, go to Relations
6) Relations that were added do not appear

Check to see if this is an error of Relations not saving in a list, or Update Relations page not reading the relations from the DB. 

Please update the Update/Copy module Relations pages to read selected lists relations from DB.

**Comment by CQTdev** [comment]
Edited, working in Browse, need to get working in Update/Copy

**Comment by acoughlin** [comment]
Edited, working in Browse, need to get working in Update/Copy

**Comment by acoughlin** [comment]
Edit again, I am not sure if it is truly working in Browse... I have seen it work, and seen it not work.

**Comment by zmeenakshi** [comment]
This is working in Browse & Search and Update modules. The Copy module has still under development, so won't appear until that is complete.

**Comment by zmeenakshi** [comment]
Alexander, please retest, confirm and if resolved close the ticket.
