### ISSUE TITLE
Relations Page and Hierarchy Search Not Functional in Update/Copy

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#57]
Module: Update/Copy
Page: Relations

Implement the Relations page in Update and Copy modules as it is implemented in the Create module, with working hierarchy search, adding relations, deleting, saving relations, etc.

**Comment by vireshwali** [comment]
fixed in update....leyla is looking into the issue about why buttons not working in update when the same work in create.

**Comment by vireshwali** [comment]
fixed in update for updating existing ones and inserting new ones. Will check in copy as well.

**Comment by zmeenakshi** [comment]
Working in update module.
