### ISSUE TITLE
Warning on clicking on the 'Next' button

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#59]
Module - Create/Copy/Update
Page - Details, Informative Notes, Relations

1) Clicking on Next button should show a warning message as mentioned “You have unsaved changes on this page. Do you want to leave this page and discard your changes”, if unsaved changes are detected.
2) If user chooses “Yes” the, updates are not saved and next form is displayed.

**Comment by andmiel81** [comment]
Does this apply to jump by tab clicking, too?

**Comment by zmeenakshi** [comment]
Yes.

**Comment by zmeenakshi** [comment]
Priority: High (to be completed by 9-March-2017)

**Comment by zmeenakshi** [comment]
Leyla, I not clear how we need to build this for Create-> Add Details page. I don't user should be able to move to the next form (Informative Notes) if they don't save the changes. The tabs should be enabled after ONLY
 one saves the data in Add Details.

**Comment by andmiel81** [comment]
I have added the change detection and confirm message show up code for "Details" and "Notes" tabs.

**Comment by zmeenakshi** [comment]
Add Details should show a warning message "You have unsaved changes on this page. Please save to continue"

**Comment by andmiel81** [comment]
added in commit bcb587bce0e0cfd1bca32b30764e2b54e78aee0b

**Comment by zmeenakshi** [comment]
showing warning message "You have unsaved changes on this page. Please save to continue"
