### ISSUE TITLE
The Format for Due Date is –DD-MMM-YYYY

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#60]
Module - Create/Update/Copy
Page - Confirm

The Format for Due Date is –DD-MMM-YYYY

**Comment by zmeenakshi** [comment]
This is still showing DD/MM/YYYY. 
![duedate](https://cloud.githubusercontent.com/assets/25993316/23404837/1ad0ac18-fddd-11e6-880f-094b96aad1f3.PNG)

**Comment by lsalim** [comment]
![image](https://cloud.githubusercontent.com/assets/5912923/23477507/0f3feb3c-feb6-11e6-9237-47ea27ae0634.png)
