### ISSUE TITLE
Update - Hierarchy Search is not retrieving PRO, SMQ 1 to SM5, SOC, HLGT, HLT, PT and LLT terms

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#61]
Module - Update
Form - Relations

1) Hierarchy Search is not retrieving PRO, SMQ 1 to SM5, SOC, HLGT, HLT, PT, and LLT terms.

**Comment by vireshwali** [comment]
marking as fixed as per Meenakshi's checks.
