### ISSUE TITLE
Default Extensions for TME, CPT, DME, TR1=1 and for PRO=2

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#63]
Module - Update/Copy
Form - Search

Defaults:
If the Extension is TME, CPT, DME, TR1 then Level should be 1.

If the Extension is PRO, level should be 2.
If the State is Draft, Reviewed and Approved the Status should be Pending.
If the State is Published then Status should be Active.

**Comment by lsalim** [comment]
For the state, the status is selected before in the search form: 
![state_status](https://cloud.githubusercontent.com/assets/5912923/23475729/4e8791b0-feb0-11e6-8731-c6e68689867c.PNG)

Should I change the position on the form for those two components ? Otherwise it won't work

**Comment by lsalim** [comment]
For now, the value of Status would change depending on State. Only the position of those 2 components seems wrong

**Comment by zmeenakshi** [comment]
Let's do it other way round.

If the Status is Pending then State should be Draft, Reviewed and Approved.
If the Status is Active then State should be Published.
