### ISSUE TITLE
Copy - Hierarchy Search - Level LOV

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#64]
Module - Create/Update/Copy
Form - Relations

PRO should not be available in the Level LOV when the list extension or type is PRO, CPT and DEM.

**Comment by lsalim** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/5912923/23582996/a476d708-012f-11e7-8ccb-b6f3a93b3ed1.png)


![image](https://cloud.githubusercontent.com/assets/5912923/23583004/cc8ce93a-012f-11e7-8876-d3b8fd93c5ea.png)
