### ISSUE TITLE
Adding and selecting MedDRA Dictionary from Codelist Type

### ISSUE THREAD

**Issue by NehaKhosa** [DBMS-Consulting/CQT2#66]
Module - Administrator
Form - Codelist Configurations

Add MedDRA Dictionary to the LOV and selecting the MedDRA Dictionary from the Codelist Type should be a similar window which will displayed only those records where interval codelist values is

**Comment by lsalim** [comment]
The comment on this task is not complete. 

> a similar window which will displayed only those records where interval codelist values is ...?
