### ISSUE TITLE
Standardize Extension Name Across Entire Application

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#71]
Module: All
Page: All

Need to standardize the Extension names across the application. For example, on the Create - Add Details page, we can select Extension: Protocol, but when we save that and go to Create - Confirm the Extension is displayed as PRO. We need to set ALL extensions across the application to use the **Full name**, in Create module, Search module, Hierarchy search, etc...

**IMPORTANT** we should eventually be able to configure this as a setting from the Administration page. So, in the administration page, we will be able to select "Display Full Name" or "Display acronym" or something along those lines. If it is possible to begin implementing this functionality, but have it currently set to display the long name until that administration page is finished, then we need to do that to save time in the future.

Priority: HIGH, needed by 8AM EST 2-28 to show customer.
Leyla please give me your thoughts on this before we begin implementing changes.

**Comment by lsalim** [comment]
Display Full Name for now

**Comment by lsalim** [comment]
PRO        : Protocol
CPT        : Critical Preferred Terms
DME        : Designated Medical Events
TME        : Targeted Medical Events
TR1        : Events of Special Clinical Interest

**Comment by lsalim** [comment]
Display Full Name for now in:

- All Confirm pages
- Details (Browse and search)

**Comment by lsalim** [comment]
For the following, we would have to save some code or data in the database:

> we should eventually be able to configure this as a setting from the Administration page. So, in the administration page, we will be able to select "Display Full Name" or "Display acronym" or something along those lines. If it is possible to begin implementing this functionality, but have it currently set to display the long name until that administration page is finished, then we need to do that to save time in the future.
