### ISSUE TITLE
Search: State Field Filter Not Working

### ISSUE THREAD

**Issue by acoughlin** [DBMS-Consulting/CQT2#72]
Module: Browse and Search
Page: Search

The filter for the State field is not working correctly. See attachment, setting State to All returns the proper result, however, setting State to Approved causes the search to return 0 results.

**After** resolving this issue please test the other filters to ensure they all work properly, and please ensure this change applies to all search pages in the other modules as well.

![image](https://cloud.githubusercontent.com/assets/12534580/23370815/ec02a9e4-fce3-11e6-8d33-44fc6ab2994b.png)

**Comment by vireshwali** [comment]
I think its working fine....
attached screenshots form Ui and form db.

![opencqt-logo](https://cloud.githubusercontent.com/assets/1810358/23412543/db4e32da-fdfb-11e6-9588-e3f4999c3b3a.png)

![capture1](https://cloud.githubusercontent.com/assets/1810358/23412554/e01b82fe-fdfb-11e6-972b-18426e080f83.PNG)

**Comment by acoughlin** [comment]
This is resolved
