### ISSUE TITLE
Create / Update: User should NOT be able to change the list attributes and informative notes and Relations when CMQ_STATE is APPROVED or PUBLISHED.

### ISSUE THREAD

**Issue by lsalim** [DBMS-Consulting/CQT2#73]

**Comment by zmeenakshi** [comment]
The the Details, Informative Notes and Relations are read-only in Copy module also, which is not correct. In copy we should be able to create a new list from an existing one.

**Comment by zmeenakshi** [comment]
Viresh resolved the copy module issue.

**Comment by zmeenakshi** [comment]
It is back to previous state. The system should prevent user from updating (Details and Informative Notes and Relations) if state is not Draft and Review.

**Comment by lsalim** [comment]
This is working.
