### ISSUE TITLE
Update -> Search; Reset button is NOT working.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#77]

**Comment by lsalim** [comment]
It is working fine.
SEARCH:
![image](https://cloud.githubusercontent.com/assets/5912923/23477251/49b5d55c-feb5-11e6-9698-ea5bfd313e28.png)


AFTER RESET:
![image](https://cloud.githubusercontent.com/assets/5912923/23477268/5ae45cf4-feb5-11e6-90e2-c52d6e036926.png)
