### ISSUE TITLE
Details and Confirm: The Creation date format is inconsistent. On Details is shows Tue Feb 28 03:11:47 EST 2017 while on Confirm 2017-02-28

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#79]

**Comment by vireshwali** [comment]
can u tell me which UI?  am seeing the same format for both in update ui.

**Comment by zmeenakshi** [comment]
Confirm and Details form

Date format: [YYYY-MMM-DD HH:MM:SS]

**Comment by zmeenakshi** [comment]
[DateFormat.docx](https://github.com/DBMS-Consulting/CQT2/files/818649/DateFormat.docx)

**Comment by zmeenakshi** [comment]
Date format should be  [YYYY-MMM-DD HH:MM:SS]

**Comment by andmiel81** [comment]
it seems that the creation date is stored date only.
So when put in format of  [YYYY-MMM-DD HH:MM:SS], time part is always 00:00:00

**Comment by zmeenakshi** [comment]
Time is not always 00:00:00. Please see screenshot.

![image](https://cloud.githubusercontent.com/assets/25993316/23580735/2b03527c-012d-11e7-8832-a8e80b69c9bf.png)

Also, can you check why LAST_MODIFIED_BY and LAST_MODICATION_DATE columns are not populated upon updating list (or CMQ).

**Comment by vireshwali** [comment]
last modified time thing is fixed with my last commit...
its getting updated correctly now in relations and base tables

**Comment by zmeenakshi** [comment]
We need still need to look at the Creation Date issue.
