### ISSUE TITLE
Is the functionality to renumber the serial numbers present in the Administration form?

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#82]
This is important for when a value needs to be added between 2 serial numbers in the codelist, and the user wants this to be reordered.

For example, we will need to add "All Products"  But this will be a high serial number appearing at the end of the list.  And the user will not want to manually change the serial numbers to put this at Serial Number 2, which is where it should be.

**Comment by zmeenakshi** [comment]
I do not see Add and Cancel button any more and Edit column is also not present.
![adminform](https://cloud.githubusercontent.com/assets/25993316/23405915/75b0ef3a-fde2-11e6-9846-8974a2f048c9.PNG)

**Comment by lsalim** [comment]
I don't think the functionnality is present yet

**Comment by zmeenakshi** [comment]
Then we need to add this. Please prioritize this.

**Comment by zmeenakshi** [comment]
Also, can you check what happened to Add and cancel button, and the edit column in extreme right.

**Comment by zmeenakshi** [comment]
When adding a new codelist the Serial# should be auto-populated incrementally, but at the same time should be enterable.
Also, the system must renumber the serial# if a serial# of any codelist is changed to bring it up and down the list.

**Comment by lsalim** [comment]
Commit done for the auto populating and the list are charged at the beginning . Much faster
