### ISSUE TITLE
Administrator: All codelist values are read with an ACTIVE_FLAG='Y' condition, so that codelist values CAN be updated by an administrator.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#83]

**Comment by zmeenakshi** [comment]
The extension drop-down is displaying inactive codelist value.
![extension](https://cloud.githubusercontent.com/assets/25993316/23493607/07d8a9f6-ff33-11e6-888e-7b7885218d0c.PNG)
![extension_lov](https://cloud.githubusercontent.com/assets/25993316/23493627/2df15b42-ff33-11e6-9b7a-2e38d1241f0a.PNG)

**Comment by lsalim** [comment]
Fixed in the service method
