### ISSUE TITLE
Administrator -> Multiple issues.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#87]
New row is NOT inserted on clicking the add button.
Value for Active is N for all codelist values. Whereas, at this point in time all are active.
Default flag should be Y for seq# 1, where it is N.
![admin](https://cloud.githubusercontent.com/assets/25993316/23468174/17052458-fec6-11e6-9de9-503a9578948b.PNG)

**Comment by lsalim** [comment]
Those values are taken directly from the database. Do you want me to change how they are shown in the form?

**Comment by zmeenakshi** [comment]
No, there is NO need to change anything. Just pull what is in DB as shown in the screenshots.

![extension](https://cloud.githubusercontent.com/assets/25993316/23493551/a48923c6-ff32-11e6-9072-534b84d42b4c.PNG)
![ref_codelist_config](https://cloud.githubusercontent.com/assets/25993316/23493556/a9709c98-ff32-11e6-9673-bb9cf43eedc0.PNG)

**Comment by lsalim** [comment]
Fixed and committed
