### ISSUE TITLE
The system is not saving association created between PARENT and CHILD list.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#88]
Without the parent association, the system won't be able to tell who is the parent and child when any 2 lists are associated to each other. Hence Publishing list with PARENT and CHILD relation is not working.

And we need some kind of constraint to say that the same related terms can not be duplicated for the same CMQ_CODE and CMQ_ID combination

**Comment by zmeenakshi** [comment]
![cmq_parent_name and code empty](https://cloud.githubusercontent.com/assets/25993316/23494769/bdb24b04-ff3a-11e6-86b0-5af6663540c2.png)

**Comment by vireshwali** [comment]
fixed in update. will check in create and copy as  well.

**Comment by vireshwali** [comment]
fixed in create as well.
