### ISSUE TITLE
Search is not returning Pfizer data loaded in to the database.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#89]
![pfizer_data](https://cloud.githubusercontent.com/assets/25993316/23493892/314f385c-ff35-11e6-9e86-9a04e31460a9.PNG)
![no_pfizer_ui](https://cloud.githubusercontent.com/assets/25993316/23493894/33d7ec5e-ff35-11e6-8ff3-caaeedac76b4.PNG)
![db_pfizerdata](https://cloud.githubusercontent.com/assets/25993316/23493895/3546fb20-ff35-11e6-9a42-cf250284dac1.PNG)

**Comment by zmeenakshi** [comment]
Adding comments as per our discussion on skype.
The data that  entered from UI has a different CMQ_PROGRAM_CD, CMQ_PROTOCOL_CD and CMQ_PRODUCT_CD are different from ones the loaded.

For loaded ones contains codelist_internal_value and ones entered from the UI store codelist_values instead of codelist_internal_values for all _CD columns.

Entered from UI:
![enter from ui](https://cloud.githubusercontent.com/assets/25993316/23579216/c20dbf78-010e-11e7-8a3b-7bdbcc3aed87.png)

Loaded in to the DB:
![loaded in to the db](https://cloud.githubusercontent.com/assets/25993316/23579217/c210f0d0-010e-11e7-95d3-1288e3fb75e1.png)

**Comment by lsalim** [comment]
Fixed on details and search.
But database must be reset.

**Comment by zmeenakshi** [comment]
The issue has coming again.

**Comment by zmeenakshi** [comment]
Confirmed. Pfizer data is showing up.

![image](https://cloud.githubusercontent.com/assets/25993316/23608947/bb170aec-0291-11e7-88f0-c1adfa355bc4.png)
