### ISSUE TITLE
Hide next button on the Search page.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#90]
![search_nextbutton](https://cloud.githubusercontent.com/assets/25993316/23494070/55949242-ff36-11e6-980f-8c3d85e74511.PNG)

**Comment by andmiel81** [comment]
patch has been applied : commit cc97a41

**Comment by andmiel81** [comment]
Along with this on "Update" and "Copy" page, disabled jump to other tabs(Details, Information Notes, Relations, etc) without searching and selecting.
