### ISSUE TITLE
Fixed the layout of Informative Notes section in the Confirm from.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#91]
![informative_notes](https://cloud.githubusercontent.com/assets/25993316/23499632/e348c9ac-ff52-11e6-84c1-437a82446f97.PNG)

**Comment by andmiel81** [comment]
patch has been applied: 7c31112

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/23574514/f50a1414-0076-11e7-9a15-1cab563241f9.png)
fixes
