### ISSUE TITLE
Confirm : Disabled buttons do not like disabled.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#93]
In the screenshot, Retire, Reactive, Demote to Draft and Approve for disabled, but they don't look disabled.

![disabledbuttons](https://cloud.githubusercontent.com/assets/25993316/23499939/270f04fc-ff54-11e6-9915-f1fe527ad24e.PNG)

**Comment by lsalim** [comment]
Was already fixed
