### ISSUE TITLE
publishCurrentVersion.xhtml picklist not updating after promote action

### ISSUE THREAD

**Issue by vireshwali** [DBMS-Consulting/CQT2#96]
see `com.dbms.controller.PublishController.promoteTargetList()` mthod line 163 inside the else block of `if(hasErrorOccured)`

The action works fine and promotes as needed but the update of the UI does not seem to be reflecting on the UI.

After publish is successful, the right side list in the UI should be cleaned or erased and left side list should be updated. The controller is fixed with this code and the setter is also called for the dual list, the response in browser (i checked in firefox firebug) also seems to be right  but the browser on screen Ui is not updating to reflect the new values for the right and left side list.

**Comment by lsalim** [comment]
Panel is cleared after promoting:

![image](https://cloud.githubusercontent.com/assets/5912923/23583163/37becf94-0134-11e7-80eb-a697f9fc7261.png)
