### ISSUE TITLE
Search is not retrieving Pfizer data.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#97]
Module: Create/Update/Copy/Browse & Search
Form: Search

The Pfizer data is not retrieved. The data loaded with codelist_internal_values PROGRAM_CD, PROTOCOL_CD, PRODUCT_CD, which is correct. The lists entered from UI are storing codelist_values in PROGRAM_CD, PROTOCOL_CD, PRODUCT_CD instead of codelist_internal_value, this is incorrect. 

And it looks like the Program, Protocol and Product criteria are searching by codelist_values instead of codelist_internal_values.

Leyla, please coordinate with Andrius Mielkus to resolve this ASAP. Please ensure the State should display and show the values as per WORKFLOW_STATES in configuration_codelist_type column.

**Comment by lsalim** [comment]
Please test to see if the above description has ben fixed.
