### ISSUE TITLE
Search by Level "All" is not returning record.

### ISSUE THREAD

**Issue by zmeenakshi** [DBMS-Consulting/CQT2#99]
Module: Update/Copy/Browse & Search
Form: Search

When setting search to 'All' for level, the system is not retrieving records.

![image](https://cloud.githubusercontent.com/assets/25993316/23581070/8728ca04-0133-11e7-984f-7153490df459.png)

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/23584313/b53c2f22-0155-11e7-9427-d04594f684f5.png)

It's working when I tested.
Please let me know how to reproduce this bug.

**Comment by zmeenakshi** [comment]
That's not true. Please see this screenshot.

![image](https://cloud.githubusercontent.com/assets/25993316/23585958/17725da0-01b1-11e7-88a3-88e6992ed073.png)

Can you check this on Leyla's commit as she fixed the codelist issue to determine if this is still an issue.

**Comment by andmiel81** [comment]
![image](https://cloud.githubusercontent.com/assets/22034392/23589807/4409f16e-01cc-11e7-8c3c-3b8466f1aeee.png)
fixed with 348fb4c

**Comment by zmeenakshi** [comment]
This is not working again.

**Comment by zmeenakshi** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/25993316/23608781/0544bcaa-0291-11e7-9837-4baab8503bed.png)
